import React, { createContext, useContext, useState } from 'react';

export type LanguageCode = 'en' | 'hi' | 'pa' | 'bn' | 'mr' | 'te' | 'ta' | 'gu';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  native: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी' },
  { code: 'pa', label: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা' },
  { code: 'mr', label: 'Marathi', native: 'मराठी' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்' },
  { code: 'gu', label: 'Gujarati', native: 'ગુજરાતી' }
];

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    commandCenter: 'Campaign Command Center',
    commandCenterSub: 'Real-time ground overview for Gram Panchayat Rampur election war room.',
    campaignTeam: 'Campaign Team & Permissions',
    teamDescription: 'Add, edit, and assign campaign managers (Admins) and ward booth incharge (Volunteers).',
    candidateCenter: 'Candidate Management Center',
    candidateDescription: 'Profiles, official election symbols, slogans, and campaign assets for contesting candidates.',
    voterDatabase: 'Voter Roll & Contact Database',
    voterDatabaseDesc: 'Official voter list management with CSV sync and camera-based OCR list extraction.',
    studioTitle: 'Design Studio & Campaign Assets',
    studioSub: 'Generate high-resolution pamphlets, flex banners, and WhatsApp status cards with official symbols.',
    broadcastTitle: 'Broadcast & Messaging Center',
    broadcastSub: 'Personalized mobile outreach with automated WhatsApp-to-SMS fallback routing.',
    boothOps: 'Booth Operations & Panna Roster',
    surveysComplaints: 'Surveys & Citizen Complaints',
    expensesLedger: 'Expenses Ledger',
    turnoutAnalytics: 'Turnout Analytics',
    settingsBranding: 'Settings & Branding',
    totalVoters: 'Total Voters',
    whatsappReached: 'WhatsApp Reached',
    activeTeam: 'Active Team',
    budgetUtilized: 'Budget Spent',
    searchVoters: 'Search by voter name, mobile, ward, or EPIC ID...',
    allSegments: 'All Voters',
    exportCsv: 'Export CSV',
    uploadRoll: 'Upload CSV / PDF',
    scanOcr: 'Camera OCR Scanner',
    addCandidate: '+ Add Candidate',
    addMember: '+ Add Team Member',
    logGrievance: '+ Log Grievance',
    addExpense: '+ Add Expense',
    dispatchBroadcast: 'Dispatch Broadcast',
    dontHaveAccount: "Don't have an account? Sign up",
    alreadyAccount: 'Already have an account? Log in',
    continueDemo: 'Continue Demo without Login',
    roleSwitcher: 'ElectWin Role Switcher'
  },
  hi: {
    commandCenter: 'चुनाव अभियान वॉर रूम',
    commandCenterSub: 'ग्राम पंचायत रामपुर चुनाव के लिए ग्राउंड स्तर का लाइव डेटा।',
    campaignTeam: 'अभियान टीम एवं अधिकार',
    teamDescription: 'प्रबंधक (Admin) और वार्ड पन्ना प्रमुख (Volunteer) जोड़ें एवं प्रबंधित करें।',
    candidateCenter: 'उम्मीदवार प्रबंधन केंद्र',
    candidateDescription: 'सरपंच एवं पंच प्रत्याशियों के प्रोफाइल, चुनाव चिह्न और घोषणापत्र।',
    voterDatabase: 'मतदाता सूची एवं संपर्क डेटाबेस',
    voterDatabaseDesc: 'आधिकारिक वोटर लिस्ट, CSV सिंक और कैमरा OCR वोटर पर्ची स्कैनर।',
    studioTitle: 'डिज़ाइन स्टूडियो एवं प्रचार सामग्री',
    studioSub: 'आधिकारिक चुनाव चिह्नों के साथ पोस्टर, फ्लेक्स बैनर एवं स्टेटस कार्ड बनाएं।',
    broadcastTitle: 'मैसेजिंग एवं ब्रॉडकास्ट सेंटर',
    broadcastSub: 'व्हाट्सएप एवं ऑटोमैटिक SMS फॉलबैक के साथ सीधे मतदाताओं तक संदेश।',
    boothOps: 'बूथ संचालन एवं पन्ना प्रमुख',
    surveysComplaints: 'जनसमस्याएं एवं शिकायतें',
    expensesLedger: 'चुनाव खर्च रजिस्टर',
    turnoutAnalytics: 'मतदान एवं रुझान विश्लेषण',
    settingsBranding: 'सेटिंग्स एवं ब्रांडिंग',
    totalVoters: 'कुल मतदाता',
    whatsappReached: 'व्हाट्सएप संपर्क',
    activeTeam: 'सक्रिय कार्यकर्ता',
    budgetUtilized: 'खर्च की गई राशि',
    searchVoters: 'मतदाता का नाम, मोबाइल नंबर या वार्ड खोजें...',
    allSegments: 'सभी मतदाता',
    exportCsv: 'CSV डाउनलोड',
    uploadRoll: 'लिस्ट अपलोड करें',
    scanOcr: 'वोटर पर्ची स्कैन (OCR)',
    addCandidate: '+ नया प्रत्याशी जोड़ें',
    addMember: '+ सदस्य जोड़ें',
    logGrievance: '+ समस्या दर्ज करें',
    addExpense: '+ नया खर्च जोड़ें',
    dispatchBroadcast: 'संदेश भेजें',
    dontHaveAccount: 'खाता नहीं है? साइन अप करें',
    alreadyAccount: 'पहले से खाता है? लॉगिन करें',
    continueDemo: 'डेमो मोड में आगे बढ़ें',
    roleSwitcher: 'भूमिका (Role) बदलें'
  },
  pa: {
    commandCenter: 'ਚੋਣ ਮੁਹਿੰਮ ਕਮਾਂਡ ਸੈਂਟਰ',
    commandCenterSub: 'ਗ੍ਰਾਮ ਪੰਚਾਇਤ ਰਾਮਪੁਰ ਚੋਣਾਂ ਦਾ ਲਾਈਵ ਡਾਟਾ।',
    campaignTeam: 'ਮੁਹਿੰਮ ਟੀਮ ਅਤੇ ਅਧਿਕਾਰ',
    teamDescription: 'ਪ੍ਰਬੰਧਕ ਅਤੇ ਵਾਰਡ ਬੂਥ ਇੰਚਾਰਜ ਸ਼ਾਮਲ ਕਰੋ।',
    candidateCenter: 'ਉਮੀਦਵਾਰ ਪ੍ਰਬੰਧਨ ਕੇਂਦਰ',
    candidateDescription: 'ਚੋਣ ਨਿਸ਼ਾਨ ਅਤੇ ਮੈਨੀਫੈਸਟੋ ਪ੍ਰਬੰਧਨ।',
    voterDatabase: 'ਵੋਟਰ ਸੂਚੀ ਅਤੇ ਡਾਟਾਬੇਸ',
    voterDatabaseDesc: 'ਸਰਕਾਰੀ ਵੋਟਰ ਸੂਚੀ ਅਤੇ ਕੈਮਰਾ OCR ਸਕੈਨਰ।',
    studioTitle: 'ਡਿਜ਼ਾਈਨ ਸਟੂਡੀਓ',
    studioSub: 'ਪੋਸਟਰ, ਫਲੈਕਸ ਬੈਨਰ ਅਤੇ ਵਟਸਐਪ ਕਾਰਡ ਬਣਾਓ।',
    broadcastTitle: 'ਸੁਨੇਹਾ ਕੇਂਦਰ',
    broadcastSub: 'ਵਟਸਐਪ ਅਤੇ SMS ਸੁਨੇਹੇ ਭੇਜੋ।',
    boothOps: 'ਬੂਥ ਸੰਚਾਲਨ',
    surveysComplaints: 'ਸ਼ਿਕਾਇਤਾਂ ਅਤੇ ਮੁੱਦੇ',
    expensesLedger: 'ਖਰਚਾ ਰਜਿਸਟਰ',
    turnoutAnalytics: 'ਵੋਟਿੰਗ ਵਿਸ਼ਲੇਸ਼ਣ',
    settingsBranding: 'ਸੈਟਿੰਗਾਂ',
    totalVoters: 'ਕੁੱਲ ਵੋਟਰ',
    whatsappReached: 'ਵਟਸਐਪ ਪਹੁੰਚ',
    activeTeam: 'ਸਰਗਰਮ ਟੀਮ',
    budgetUtilized: 'ਖਰਚਿਆ ਬਜਟ',
    searchVoters: 'ਵੋਟਰ ਲੱਭੋ...',
    allSegments: 'ਸਾਰੇ ਵੋਟਰ',
    exportCsv: 'CSV ਡਾਊਨਲੋਡ',
    uploadRoll: 'ਫਾਈਲ ਅੱਪਲੋਡ',
    scanOcr: 'OCR ਸਕੈਨ',
    addCandidate: '+ ਉਮੀਦਵਾਰ ਸ਼ਾਮਲ ਕਰੋ',
    addMember: '+ ਮੈਂਬਰ ਸ਼ਾਮਲ ਕਰੋ',
    logGrievance: '+ ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
    addExpense: '+ ਖਰਚ ਸ਼ਾਮਲ ਕਰੋ',
    dispatchBroadcast: 'ਸੁਨੇਹਾ ਭੇਜੋ',
    dontHaveAccount: 'ਖਾਤਾ ਨਹੀਂ ਹੈ? ਸਾਈਨ ਅੱਪ ਕਰੋ',
    alreadyAccount: 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ? ਲੌਗਇਨ ਕਰੋ',
    continueDemo: 'ਬਿਨਾਂ ਲੌਗਇਨ ਅੱਗੇ ਵਧੋ',
    roleSwitcher: 'ਰੋਲ ਬਦਲੋ'
  },
  bn: {
    commandCenter: 'নির্বাচনী কমান্ড সেন্টার',
    commandCenterSub: 'গ্রাম পঞ্চায়েত রামপুর নির্বাচনের লাইভ ওভারভিউ।',
    campaignTeam: 'প্রচার দল ও অনুমতি',
    teamDescription: 'টিম সদস্য ও বুথ ইনচার্জ যোগ করুন।',
    candidateCenter: 'প্রার্থী ব্যবস্থাপনা কেন্দ্র',
    candidateDescription: 'প্রার্থী প্রোফাইল এবং প্রতীক।',
    voterDatabase: 'ভোটার তালিকা ডেটাবেস',
    voterDatabaseDesc: 'ভোটার তালিকা ব্যবস্থাপনা ও OCR স্ক্যানার।',
    studioTitle: 'ডিজাইন স্টুডিও',
    studioSub: 'পোস্টার ও ব্যানার জেনারেটর।',
    broadcastTitle: 'ব্রডকাস্ট সেন্টার',
    broadcastSub: 'হোয়াটসঅ্যাপ ও এসএমএস বার্তা পাঠান।',
    boothOps: 'বুথ কার্যক্রম',
    surveysComplaints: 'অভিযোগ ও সমীক্ষা',
    expensesLedger: 'খরচ লেজার',
    turnoutAnalytics: 'টার্নআউট অ্যানালিটিক্স',
    settingsBranding: 'সেটিংস ও ব্র্যান্ডিং',
    totalVoters: 'মোট ভোটার',
    whatsappReached: 'হোয়াটসঅ্যাপ পৌঁছেছে',
    activeTeam: 'সক্রিয় দল',
    budgetUtilized: 'ব্যয়িত বাজেট',
    searchVoters: 'ভোটার খুঁজুন...',
    allSegments: 'সব ভোটার',
    exportCsv: 'CSV এক্সপোর্ট',
    uploadRoll: 'আপলোড',
    scanOcr: 'OCR স্ক্যান',
    addCandidate: '+ প্রার্থী যোগ করুন',
    addMember: '+ সদস্য যোগ করুন',
    logGrievance: '+ অভিযোগ লিখুন',
    addExpense: '+ খরচ যোগ করুন',
    dispatchBroadcast: 'বার্তা পাঠান',
    dontHaveAccount: 'অ্যাকাউন্ট নেই? সাইন আপ করুন',
    alreadyAccount: 'অ্যাকাউন্ট আছে? লগইন করুন',
    continueDemo: 'ডেমো মোডে চালিয়ে যান',
    roleSwitcher: 'রোল পরিবর্তন'
  },
  mr: {
    commandCenter: 'निवडणूक मोहीम वॉर रूम',
    commandCenterSub: 'ग्रामपंचायत रामपूर निवडणुकीचा थेट आढावा.',
    campaignTeam: 'मोहीम टीम आणि परवानग्या',
    teamDescription: 'मोहीम व्यवस्थापक आणि बूथ प्रमुख जोडा.',
    candidateCenter: 'उमेदवार व्यवस्थापन केंद्र',
    candidateDescription: 'उमेदवार प्रोफाइल, चिन्ह आणि जाहीरनामा.',
    voterDatabase: 'मतदार यादी व डेटाबेस',
    voterDatabaseDesc: 'मतदार यादी व्यवस्थापन आणि कॅमेरा OCR स्कॅनर.',
    studioTitle: 'डिझाइन स्टुडिओ',
    studioSub: 'पोस्टर, बॅनर आणि व्हॉट्सअॅप स्टेटस कार्ड तयार करा.',
    broadcastTitle: 'प्रसारण व संदेश केंद्र',
    broadcastSub: 'व्हॉट्सअॅप आणि एसएमएस द्वारे थेट मतदारांपर्यंत पोहोचा.',
    boothOps: 'बूथ कामकाज',
    surveysComplaints: 'तक्रारी व सर्वेक्षण',
    expensesLedger: 'खर्च नोंदवही',
    turnoutAnalytics: 'मतदान विश्लेषण',
    settingsBranding: 'सेटिंग्ज व ब्रँडिंग',
    totalVoters: 'एकूण मतदार',
    whatsappReached: 'व्हॉट्सअॅप संपर्क',
    activeTeam: 'सक्रिय टीम',
    budgetUtilized: 'खर्च केलेला निधी',
    searchVoters: 'मतदार शोधा...',
    allSegments: 'सर्व मतदार',
    exportCsv: 'CSV डाउनलोड',
    uploadRoll: 'यादी अपलोड करा',
    scanOcr: 'OCR स्कॅन',
    addCandidate: '+ उमेदवार जोडा',
    addMember: '+ सदस्य जोडा',
    logGrievance: '+ तक्रार नोंदवा',
    addExpense: '+ खर्च जोडा',
    dispatchBroadcast: 'संदेश पाठवा',
    dontHaveAccount: 'खाते नाही? साइन अप करा',
    alreadyAccount: 'आधीच खाते आहे? लॉगिन करा',
    continueDemo: 'लॉगिन न करता डेमो पाहा',
    roleSwitcher: 'भूमिका बदला'
  },
  te: {
    commandCenter: 'ఎన్నికల ప్రచార కమాండ్ సెంటర్',
    commandCenterSub: 'గ్రామ పంచాయతీ రాంపూర్ ఎన్నికల ప్రత్యక్ష సమాచారం.',
    campaignTeam: 'ప్రచార బృందం & అనుమతులు',
    teamDescription: 'మేనేజర్లు మరియు బూత్ ఇన్‌ఛార్జ్‌లను జోడించండి.',
    candidateCenter: 'అభ్యర్థుల నిర్వహణ కేంద్రం',
    candidateDescription: 'అభ్యర్థుల ప్రొఫైల్స్, చిహ్నాలు మరియు మేనిఫెస్టో.',
    voterDatabase: 'ఓటరు జాబితా & డేటాబేస్',
    voterDatabaseDesc: 'ఓటరు జాబితా నిర్వహణ & OCR స్కానర్.',
    studioTitle: 'డిజైన్ స్టూడియో',
    studioSub: 'పోస్టర్లు, ఫ్లెక్స్ బ్యానర్లు తయారు చేయండి.',
    broadcastTitle: 'సందేశ కేంద్రం',
    broadcastSub: 'వాట్సాప్ & SMS ద్వారా ఓటర్లకు సందేశాలు పంపండి.',
    boothOps: 'బూత్ కార్యకలాపాలు',
    surveysComplaints: 'ఫిర్యాదులు & సర్వేలు',
    expensesLedger: 'ఖర్చుల లెడ్జర్',
    turnoutAnalytics: 'ఓటింగ్ విశ్లేషణ',
    settingsBranding: 'సెట్టింగ్‌లు',
    totalVoters: 'మొత్తం ఓటర్లు',
    whatsappReached: 'వాట్సాప్ రీచ్',
    activeTeam: 'క్రియాశీల బృందం',
    budgetUtilized: 'ఖర్చు చేసిన బడ్జెట్',
    searchVoters: 'ఓటరును వెతకండి...',
    allSegments: 'అందరు ఓటర్లు',
    exportCsv: 'CSV డౌన్‌లోడ్',
    uploadRoll: 'అప్‌లోడ్ చేయండి',
    scanOcr: 'OCR స్కాన్',
    addCandidate: '+ అభ్యర్థిని జోడించండి',
    addMember: '+ సభ్యుడిని జోడించండి',
    logGrievance: '+ ఫిర్యాదు నమోదు చేయండి',
    addExpense: '+ ఖర్చును జోడించండి',
    dispatchBroadcast: 'సందేశం పంపండి',
    dontHaveAccount: 'ఖాతా లేదా? సైన్ అప్ చేయండి',
    alreadyAccount: 'ఖాతా ఉందా? లాగిన్ అవ్వండి',
    continueDemo: 'డెమో కొనసాగించండి',
    roleSwitcher: 'పాత్రను మార్చండి'
  },
  ta: {
    commandCenter: 'தேர்தல் பிரச்சார கட்டளை மையம்',
    commandCenterSub: 'கிராம பஞ்சாயத்து ராம்பூர் தேர்தல் நேரலை கண்ணோட்டம்.',
    campaignTeam: 'பிரச்சாரக் குழு மற்றும் அனுமதிகள்',
    teamDescription: 'நிர்வாகிகள் மற்றும் பூத் பொறுப்பாளர்களை சேர்க்கவும்.',
    candidateCenter: 'வேட்பாளர் மேலாண்மை மையம்',
    candidateDescription: 'வேட்பாளர் விவரங்கள், சின்னங்கள் மற்றும் தேர்தல் அறிக்கை.',
    voterDatabase: 'வாக்காளர் பட்டியல் தரவுத்தளம்',
    voterDatabaseDesc: 'வாக்காளர் பட்டியல் மேலாண்மை & OCR ஸ்கேனர்.',
    studioTitle: 'வடிவமைப்பு ஸ்டுடியோ',
    studioSub: 'சுவரொட்டிகள், பேனர்கள் மற்றும் வாட்ஸ்அப் கார்டுகள் உருவாக்கவும்.',
    broadcastTitle: 'செய்தி ஒளிபரப்பு மையம்',
    broadcastSub: 'வாட்ஸ்அப் மற்றும் SMS வழியே செய்தி அனுப்பவும்.',
    boothOps: 'பூத் செயல்பாடுகள்',
    surveysComplaints: 'புகார்கள் & ஆய்வுகள்',
    expensesLedger: 'செலவு கணக்கு',
    turnoutAnalytics: 'வாக்குப்பதிவு பகுப்பாய்வு',
    settingsBranding: 'அமைப்புகள் & பிராண்டிங்',
    totalVoters: 'மொத்த வாக்காளர்கள்',
    whatsappReached: 'வாட்ஸ்அப் சென்றடைந்தது',
    activeTeam: 'செயலில் உள்ள குழு',
    budgetUtilized: 'செலவிடப்பட்ட நிதி',
    searchVoters: 'வாக்காளரைத் தேடுங்கள்...',
    allSegments: 'அனைத்து வாக்காளர்கள்',
    exportCsv: 'CSV பதிவிறக்கம்',
    uploadRoll: 'பதிவேற்றம்',
    scanOcr: 'OCR ஸ்கேன்',
    addCandidate: '+ வேட்பாளரைச் சேர்',
    addMember: '+ உறுப்பினரைச் சேர்',
    logGrievance: '+ புகார் பதிவு செய்',
    addExpense: '+ செலவு சேர்',
    dispatchBroadcast: 'செய்தி அனுப்புக',
    dontHaveAccount: 'கணக்கு இல்லையா? பதிவு செய்க',
    alreadyAccount: 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக',
    continueDemo: 'டெமோ தொடரவும்',
    roleSwitcher: 'பங்கை மாற்றவும்'
  },
  gu: {
    commandCenter: 'ચૂંટણી પ્રચાર કમાન્ડ સેન્ટર',
    commandCenterSub: 'ગ્રામ પંચાયત રામપુર ચૂંટણી માટે લાઇવ ઓવરવ્યૂ.',
    campaignTeam: 'પ્રચાર ટીમ અને પરવાનગીઓ',
    teamDescription: 'મેનેજર અને બૂથ ઇન્ચાર્જ ઉમેરો.',
    candidateCenter: 'ઉમેદવાર વ્યવસ્થાપન કેન્દ્ર',
    candidateDescription: 'ઉમેદવાર પ્રોફાઇલ, ચૂંટણી પ્રતીક અને ઘોષણાપત્ર.',
    voterDatabase: 'મતદાર યાદી ડેટાબેઝ',
    voterDatabaseDesc: 'મતદાર યાદી વ્યવસ્થાપન અને કેમેરા OCR સ્કેનર.',
    studioTitle: 'ડિઝાઇન સ્ટુડિયો',
    studioSub: 'પોસ્ટર, ફ્લેક્સ બેનર અને વોટ્સએપ કાર્ડ બનાવો.',
    broadcastTitle: 'મેસેજિંગ અને બ્રોડકાસ્ટ સેન્ટર',
    broadcastSub: 'વોટ્સએપ અને SMS દ્વારા મતદારો સુધી પહોંચો.',
    boothOps: 'બૂથ કામગીરી',
    surveysComplaints: 'ફરિયાદો અને સર્વેક્ષણ',
    expensesLedger: 'ખર્ચ રજિસ્ટર',
    turnoutAnalytics: 'મતદાન વિશ્લેષણ',
    settingsBranding: 'સેટિંગ્સ અને બ્રાન્ડિંગ',
    totalVoters: 'કુલ મતદારો',
    whatsappReached: 'વોટ્સએપ પહોંચ',
    activeTeam: 'સક્રિય ટીમ',
    budgetUtilized: 'ખર્ચાયેલ બજેટ',
    searchVoters: 'મતદાર શોધો...',
    allSegments: 'બધા મતદારો',
    exportCsv: 'CSV ડાઉનલોડ',
    uploadRoll: 'યાદી અપલોડ કરો',
    scanOcr: 'OCR સ્કેન',
    addCandidate: '+ ઉમેદવાર ઉમેરો',
    addMember: '+ સભ્ય ઉમેરો',
    logGrievance: '+ ફરિયાદ નોંધો',
    addExpense: '+ ખર્ચ ઉમેરો',
    dispatchBroadcast: 'મેસેજ મોકલો',
    dontHaveAccount: 'ખાતું નથી? સાઇન અપ કરો',
    alreadyAccount: 'પહેલેથી ખાતું છે? લૉગિન કરો',
    continueDemo: 'ડેમો મોડ ચાલુ રાખો',
    roleSwitcher: 'રોલ બદલો'
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    return (localStorage.getItem('electwin_lang') as LanguageCode) || 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('electwin_lang', lang);
  };

  const t = (key: string): string => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.en;
    return dict[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
