import React, { createContext, useContext, useState } from 'react';

export type LanguageCode = 'en' | 'hi' | 'pa' | 'bn' | 'mr' | 'te' | 'ta' | 'gu';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  native: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी' },
  { code: 'pa', label: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা' },
  { code: 'mr', label: 'Marathi', native: 'मराठी' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்' },
  { code: 'gu', label: 'Gujarati', native: 'ગુજરાતી' }
];

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    commandCenter: 'Campaign Command Center',
    commandCenterSub: 'Real-time ground overview for Gram Panchayat Rampur election war room.',
    campaignTeam: 'Campaign Team & Permissions',
    teamDescription: 'Add, edit, and assign campaign managers (Admins) and ward booth incharge (Volunteers).',
    candidateCenter: 'Candidate Management Center',
    candidateDescription: 'Profiles, official election symbols, slogans, and campaign assets for contesting candidates.',
    voterDatabase: 'Voter Roll & Contact Database',
    voterDatabaseDesc: 'Official voter list management with CSV sync and camera-based OCR list extraction.',
    studioTitle: 'Design Studio & Campaign Assets',
    studioSub: 'Generate high-resolution pamphlets, flex banners, and WhatsApp status cards with official symbols.',
    broadcastTitle: 'Broadcast & Messaging Center',
    broadcastSub: 'Personalized mobile outreach with automated WhatsApp-to-SMS fallback routing.',
    boothOps: 'Booth Operations & Panna Roster',
    surveysComplaints: 'Surveys & Citizen Complaints',
    expensesLedger: 'Expenses Ledger',
    turnoutAnalytics: 'Turnout Analytics',
    settingsBranding: 'Settings & Branding',
    totalVoters: 'Total Voters',
    whatsappReached: 'WhatsApp Reached',
    activeTeam: 'Active Team',
    budgetUtilized: 'Budget Spent',
    searchVoters: 'Search by voter name, mobile, ward, or EPIC ID...',
    allSegments: 'All Voters',
    exportCsv: 'Export CSV',
    uploadRoll: 'Upload CSV / PDF',
    scanOcr: 'Camera OCR Scanner',
    addCandidate: '+ Add Candidate',
    addMember: '+ Add Team Member',
    logGrievance: '+ Log Grievance',
    addExpense: '+ Add Expense',
    dispatchBroadcast: 'Dispatch Broadcast',
    dontHaveAccount: "Don't have an account? Sign up",
    alreadyAccount: 'Already have an account? Log in',
    continueDemo: 'Continue Demo without Login',
    roleSwitcher: 'ElectWin Role Switcher',
    dashboardOverview: 'Dashboard Overview',
    currentElection: 'Current Election',
    totalCandidatesOrganizations: 'Total Candidates / Organizations',
    candidatesAndOrganizations: 'Candidates & organizations',
    totalVotersAdded: 'Total Voters Added',
    liveVoterDatabase: 'Live voter database',
    activeElections: 'Active Elections',
    electionPortfolio: 'Election portfolio',
    recentActivity: 'Recent Activity',
    latestUpdates: 'Latest updates',
    last5Updates: 'Last 5 updates',
    type: 'Type',
    details: 'Details',
    time: 'Time',
    totalVotersInElection: 'Total Voters in Election',
    volunteersCount: 'Volunteers',
    activeVolunteers: 'Active Volunteers',
    messagesSentThisWeek: 'Messages Sent This Week',
    campaignReach: 'Campaign reach',
    wardCoverage: 'Ward-wise Coverage',
    coverageSummary: 'Coverage summary',
    quickActions: 'Quick Actions',
    dailyChecklist: 'Daily checklist',
    addVoter: 'Add Voter',
    createPoster: 'Create Poster',
    sendBroadcast: 'Send Broadcast',
    viewComplaints: 'View Complaints',
    wardVotersCount: 'Ward Voters',
    wardCoverageSummary: 'Your ward coverage',
    pendingTasks: 'Pending Tasks',
    todayChecklist: 'Today checklist',
    taskSummary: 'Task Summary',
    assignedVoters: 'Assigned Voters',
    assignedVoterSummary: 'Follow-up list',
    dashboardLoadError: 'Could not load dashboard data from backend',
    candidates: 'Candidates',
    organizations: 'Organizations',
    volunteers: 'Volunteers',
    recent: 'Recent',
    // Professional Copy - Candidates Page
    filterAllCandidates: 'All Candidates',
    filterSarpanch: 'Sarpanch',
    filterPanch: 'Ward Members',
    emptyCandidatesTitle: 'No Candidates Yet',
    emptyCandidatesDesc: 'Start by adding your first candidate — their profile, election symbol, and campaign message will appear here.',
    candidateAddedSuccess: 'Candidate profile created successfully!',
    candidateDeletedSuccess: 'Candidate removed from campaign.',
    candidatePhoto: 'Candidate Photo',
    uploadPhotoTitle: 'Upload Candidate Photo',
    candidateSymbol: 'Election Symbol',
    symbolLabel: 'Symbol Name',
    sloganLabel: 'Campaign Slogan',
    manifestoLabel: 'Election Manifesto & Promises',
    // Professional Copy - Voters Page
    filterAllVoters: 'All Electors',
    filterHasWhatsApp: 'With WhatsApp',
    filterNoWhatsApp: 'SMS Only',
    filterYouth: 'Youth (18-35)',
    filterWomen: 'Women',
    filterMissingContact: 'No Contact Info',
    emptyVotersTitle: 'Build Your Voter Roll',
    emptyVotersDesc: 'Upload your official voter list or add electors one by one. They\'ll appear here once imported.',
    uploadVotersList: 'Upload Voter List',
    importFromCSV: 'Import CSV / PDF List',
    addVoterManually: 'Add Single Elector',
    startOCRScanner: 'Scan Voter Slip (Camera)',
    ocrScannerTitle: 'Voter Slip Scanner',
    ocrScannerDesc: 'Take a photo of the official voter slip — ElectWin will extract name, ID, mobile, and address automatically.',
    ocrProcessing: 'Scanning voter slip... extracting data...',
    ocrSuccess: 'Scanned and ready! Review the extracted data before saving.',
    voterAddedSuccess: 'Elector added to campaign database successfully!',
    voterImportSuccess: '{{count}} electors imported from your file — review and confirm before finalizing.',
    voterMobileValidation: 'Mobile number must be 10 digits (e.g., 98290 14285)',
    voterNameRequired: 'Elector name is required',
    voterListDownload: 'Download Elector List (CSV)',
    // Professional Copy - Broadcast Page
    broadcastDraftTitle: 'Message Template',
    broadcastDraftDesc: 'Write your campaign message. Use {{tags}} to personalize for each elector ({{name}}, {{ward}}, {{symbol}}).',
    broadcastWithPoster: 'Include Campaign Poster',
    broadcastWithPosterDesc: 'Add a high-quality poster image to WhatsApp messages for maximum visual impact.',
    broadcastReady: 'Ready to Send',
    broadcastPreview: 'Message Preview (What Electors See)',
    broadcastSendTo: 'Delivery Target',
    broadcastAllWards: 'All Wards',
    broadcastSelectWards: 'Select Specific Wards',
    broadcastChannelDual: 'Smart Dual Pipeline: WhatsApp → SMS Fallback',
    broadcastWhatsAppPrimary: 'Primary Channel (WhatsApp)',
    broadcastSMSFallback: 'SMS Fallback Route',
    broadcastRichMedia: 'Rich Media + Blue Tick',
    broadcastBasicText: 'Text Only',
    broadcastSendNow: 'Send Broadcast Now',
    broadcastSchedule: 'Schedule for Later',
    broadcastSending: 'Sending to {{count}} electors...',
    broadcastSentSuccess: 'Broadcast dispatched! Delivery report incoming in a few minutes.',
    broadcastSentFailed: 'Broadcast send failed — check your message and try again.',
    broadcastEmptyTitle: 'No Messages Sent Yet',
    broadcastEmptyDesc: 'Compose and send your first campaign message to reach all electors across wards.',
    deliveryReportTitle: 'Delivery Report',
    deliveryReportDesc: 'Real-time tracking of message status across all electors.',
    deliveryStatus: 'Status',
    deliveryDelivered: 'Delivered',
    deliveryRead: 'Read',
    deliveryFailed: 'Failed',
    deliveryPending: 'Pending',
    // Professional Copy - Design Studio
    studioBlankCanvas: 'Start with a Blank Canvas',
    studioBlankDesc: 'Choose from poster, banner, or status card — customize with colors, photos, and text.',
    studioTemplateTitle: 'Choose a Campaign Template',
    studioTemplateDesc: 'Pick from proven designs — election posters, ward announcements, or promotional banners.',
    studioPhotoTitle: 'Upload Campaign Photo',
    studioPhotoDesc: 'Add a professional candidate photo, party symbol, or ward logo.',
    studioDownloadPDF: 'Download as PDF',
    studioDownloadImage: 'Download as Image',
    studioShareTemplate: 'Share Campaign Asset',
    studioDesignSaved: 'Campaign design saved to gallery!',
    studioEmptyTitle: 'Campaign Gallery',
    studioEmptyDesc: 'Create posters, banners, and status cards here — then download and share with your team.',
    // Professional Copy - Complaints Page
    complaintStatusPending: 'Awaiting Action',
    complaintStatusInProgress: 'Under Review',
    complaintStatusResolved: 'Resolved',
    emptyComplaintsTitle: 'No Complaints or Grievances Yet',
    emptyComplaintsDesc: 'Electors can lodge complaints through your contact channels — they\'ll appear here for action.',
    complaintCategory: 'Category',
    complaintPriority: 'Priority',
    complaintMarkResolved: 'Mark as Resolved',
    complaintAddedSuccess: 'Complaint logged and assigned to your team.',
    complaintResolvedSuccess: 'Complaint marked as resolved — follow-up with the elector.',
    // Professional Copy - Expenses Page
    expensesTitle: 'Campaign Budget & Expenses',
    expensesDesc: 'Track every rupee spent on campaign activities — stay within limits and maintain full transparency.',
    expenseCategoryFood: 'Food & Catering',
    expenseCategoryTransport: 'Transport & Travel',
    expenseCategoryMaterial: 'Print Material',
    expenseCategoryMedia: 'Media & Advertising',
    expenseCategoryOther: 'Other Expenses',
    expenseAddTitle: 'Log a New Expense',
    expenseAmount: 'Amount (₹)',
    expenseVendor: 'Vendor / Supplier Name',
    expenseNotes: 'Details (optional)',
    expenseReceipt: 'Upload Receipt (Photo)',
    expenseAddedSuccess: 'Expense logged — budget updated automatically.',
    emptyExpensesTitle: 'Track Your Campaign Spending',
    emptyExpensesDesc: 'Log expenses here to maintain transparency and ensure you stay within your allocated budget.',
    totalSpent: 'Total Spent',
    budgetRemaining: 'Budget Remaining',
    // Professional Copy - Analytics Page
    analyticsTitle: 'Campaign Performance & Insights',
    analyticsDesc: 'Real-time dashboards on voter reach, engagement rates, and turnout trends.',
    turnoutLabel: 'Voter Turnout',
    engagementLabel: 'Message Engagement',
    deliveryRateLabel: 'Delivery Success Rate',
    contactReachLabel: 'Reachable Electors',
    emptyAnalyticsTitle: 'No Data Yet',
    emptyAnalyticsDesc: 'Once you send broadcasts and campaigns go live, analytics will appear here.',
    // Professional Copy - Volunteers Page
    emptyVolunteersTitle: 'Booth Team Roster',
    emptyVolunteersDesc: 'Assign volunteers to wards and panna sections — manage your ground team efficiently.',
    volunteerRole: 'Role',
    volunteerWard: 'Assigned Ward',
    volunteerSections: 'Panna Sections',
    volunteerPhone: 'Contact Number',
    volunteerAddNew: 'Add New Volunteer',
    volunteerAddedSuccess: 'Volunteer added to your campaign team!',
    volunteerDeletedSuccess: 'Volunteer removed from team.',
    // Professional Copy - Settings Page
    settingsTitle: 'Campaign Settings & Branding',
    settingsDesc: 'Customize your campaign theme, manage user accounts, and configure notifications.',
    campaignName: 'Campaign Name',
    campaignColor: 'Campaign Color Theme',
    campaignColorDesc: 'Choose the primary color for all campaign materials.',
    partySymbol: 'Party Symbol',
    uploadLogo: 'Upload Party Logo',
    notificationSettings: 'Notification Preferences',
    enableEmailNotif: 'Email Notifications',
    enableSMSNotif: 'SMS Alerts',
    settingsSavedSuccess: 'Campaign settings updated!',
    // Professional Copy - General Actions
    addNew: 'Add',
    editItem: 'Edit',
    deleteItem: 'Remove',
    confirmDelete: 'Are you sure? This action cannot be undone.',
    yesDelete: 'Yes, Delete',
    noCancel: 'Cancel',
    searchPlaceholder: 'Search here...',
    noResultsFound: 'No results found — try a different search term.',
    loadingData: 'Loading data...',
    savingChanges: 'Saving changes...',
    errorLoadingData: 'Could not load data — please check your connection and try again.',
    errorSavingData: 'Save failed — please try again.',
    tryAgain: 'Try Again',
    returnToDashboard: 'Back to Dashboard',
    // Error & Success Messages for Forms and Uploads
    failedLoadingAnalytics: 'Failed to load analytics data',
    analyticsReportExported: 'Analytics Report exported!',
    failedLoadingComplaints: 'Failed to load complaints',
    grievanceRegistered: 'Citizen grievance registered successfully!',
    photoUploadedSuccessfully: 'Photo uploaded successfully',
    photoUploadFailed: 'Failed to upload photo',
    symbolUploadedSuccessfully: 'Symbol uploaded successfully',
    symbolUploadFailed: 'Failed to upload symbol',
    candidateNameRequired: 'Candidate name is required',
    positionRequired: 'Position is required',
    wardNumberRequired: 'Ward number is required',
    candidatePhotoRequired: 'Please upload a candidate photo',
    canvasNotReady: 'Canvas not ready',
    posterDownloadedSuccessfully: 'Poster downloaded successfully!',
    posterDownloadFailed: 'Failed to download poster',
    failedLoadingExpenses: 'Failed to load expenses',
    failedLoadingTeamMembers: 'Failed to load team members',
    notAuthorizedAddRole: 'You are not authorized to add this role.',
    noPermissionRemoveRole: 'You do not have permission to remove this role.',
    selectActiveElectionBeforeAdding: 'Select an active election before adding a voter.',
    failedLoadingVoters: 'Failed to load voters from backend',
    noActiveElectionSelected: 'No active election selected',
    officialVoterListDownloaded: 'Official Voter Roll CSV downloaded!',
    allCampaignSettingsSaved: '✅ All campaign settings saved successfully! Colors & theme persisted.',
    emblemLogoUploadedSuccessfully: 'Emblem logo uploaded successfully!',
    fillAllRequiredFields: 'Please fill all required fields',
    teamMembersPageTitle: 'Team Members',
    addCampaignTeamMember: 'Add Campaign Team Member',
    // Form Labels
    formLabelFirstName: 'First Name',
    formLabelLastName: 'Last Name',
    formLabelEmail: 'Email',
    formLabelPassword: 'Password',
    formLabelPhoneNumber: 'Phone Number',
    formLabelWardName: 'Ward / Area Assignment',
    formLabelRoleHierarchy: 'Role Hierarchy',
    formPlaceholderFirstName: 'e.g. Ramesh',
    formPlaceholderLastName: 'e.g. Saini',
    formPlaceholderEmail: 'e.g. member@electwin.com',
    formPlaceholderPassword: 'Create a password',
    formPlaceholderPhoneNumber: '+91 98765 43210',
    phoneExample: '9876543210',
    emailExample: 'superadmin@electwin.com',
    otpContactExample: 'name@electwin.com or 9876543210',
    notificationTaskAssigned: 'New Task Assigned',
    notificationDeadlineApproaching: 'Deadline Approaching',
    notificationActivitySubmitted: 'Activity Submitted for Review',
    notificationMarkAsRead: 'Mark as read',
    notificationDelete: 'Delete notification',
    notificationClearAll: 'Clear All Notifications',
    notificationNoNotifications: 'No notifications',
    notificationAllCaughtUp: "You're all caught up!",
    notificationUnread: 'unread',
    notificationJustNow: 'Just now',
    memberFilterAll: 'All',
    memberFilterAdmins: 'Admins',
    memberFilterVolunteers: 'Volunteers',
    memberSearchPlaceholder: 'Search team member by name, ward or role...',
    memberAssignedWard: 'Assigned Ward',
    memberVotersHandled: 'Voters Handled',
    memberAddedDate: 'Added Date',
    memberActiveStatus: 'Active',
    memberInactiveStatus: 'Inactive',
    memberEditAction: 'Edit',
    memberRemoveAction: 'Remove',
    memberSave: 'Save Member',
    memberLoading: 'Loading...',
    memberAdd: 'Add Member',
    memberCountLabel: 'Members',
    memberFilterLabel: 'All',
    memberElectorsLabel: 'Electors',
    roleAdminCampaignManager: 'Admin (Campaign Manager)',
    roleVolunteerFieldWorker: 'Volunteer (Field Worker)',
    wardAllCampaignHQ: 'All Wards (Campaign HQ)',
    teamMemberAddedSuccessPrefix: 'Team member',
    teamMemberAddedSuccessSuffix: 'added successfully!',
    teamMemberEditReadyPrefix: 'Edit flow for',
    teamMemberEditReadySuffix: 'is ready for the next backend integration.',
    teamMemberRemovePrefix: 'removal is gated by role permission and will be enforced in the backend layer.',
    // Auth Form
    createAccount: 'Create Account',
    signIn: 'Sign In',
    loginWithOtp: 'OTP Login',
    signInWithOtp: 'Login with OTP',
    chooseLoginMethod: 'Choose login method',
    chooseContactType: 'Choose contact method',
    useEmail: 'Email',
    usePhone: 'Phone',
    emailOrPhone: 'Email or Phone',
    sendOtp: 'Send OTP',
    verifyOtp: 'Verify OTP',
    verifyAndLogin: 'Verify & Login',
    otpSent: 'OTP sent successfully',
    otpSentSuccess: 'OTP sent successfully. Check your email or phone.',
    otpVerifySuccess: 'OTP verified successfully',
    otpWrong: 'OTP is incorrect. Please try again.',
    otpExpired: 'OTP has expired. Please request a new one.',
    otpBlocked: 'Too many wrong attempts. Please wait a moment and try again.',
    otpTestingHint: 'Testing hint: OTP is 123456',
    otpResend: 'Resend OTP',
    otpResendIn: 'Resend OTP in',
    otpStepOne: 'Step 1: Verify your contact',
    otpStepTwo: 'Step 2: Enter the 6-digit OTP',
    otpContactPlaceholder: 'Enter your email or phone number',
    otpInputLabel: '6-digit OTP',
    otpExpiredMessage: 'OTP expired. Please request a new code.',
    registerVerifiedAccount: 'Register Your Campaign Account',
    enterCredentials: 'Enter your email or phone number to receive a one-time code',
    firstName: 'First Name',
    enterFirstName: 'Enter your first name',
    lastName: 'Last Name',
    enterLastName: 'Enter your last name',
    emailAddress: 'Email Address',
    password: 'Password',
    createPassword: 'Create a password',
    enterPassword: 'Enter your password',
    authenticating: 'Authenticating...',
    creatingAccount: 'Creating account...',
    or: 'OR',
    alreadyHaveAccountLogin: 'Already have an account? Sign in',
    quickDemoLogin: '🎯 Quick Demo Login (Super Admin)',
    signUpNewAccount: 'Sign up to create a new campaign account',
    multiTenantNote: 'Multi-tenant · JWT Authentication · Role-based RBAC',
    realTimeElection: 'Real-time election campaign management',
    voterDataVolunteer: 'Voter data · Volunteer management · Design studio · Smart broadcast · Analytics dashboard',
    roleBasedAccess: 'Role-based access control (RBAC)',
    multiTenantOrg: 'Multi-tenant organization isolation',
    realtimeDashboard: 'Real-time dashboards and analytics',
    masterCampaignOS: '🇮🇳 Your Complete Election Campaign Toolkit',
    // Form validation
    fieldRequired: 'This field is required',
    invalidEmail: 'Please enter a valid email address',
    passwordMismatch: 'Passwords do not match',
    // Role-based access
    selectRole: 'Select Your Role',
    selectRoleForLogin: 'Choose which role you are logging in as',
    selectRoleForSignup: 'Choose which role to sign up as',
    roleSuperAdmin: 'Super Admin',
    roleAdmin: 'Admin (Candidate)',
    roleVolunteer: 'Volunteer',
    roleSuperAdminDesc: 'Full system access & organization management',
    roleAdminDesc: 'Candidate & campaign management',
    roleVolunteerDesc: 'Field activities & voter outreach',
    inviteOnlySignup: 'Invite-Only Signup',
    contactAdminSignup: 'New accounts are created by your Admin. Contact them to sign up.',
    superAdminExists: 'Super Admin account already exists. Public signup is disabled.',
    selectRoleToSignup: 'Select your role to continue (only Super Admin available for new accounts)',
    currentRole: 'Current Role',
    // Success/Error messages
    welcomeMessage: 'Welcome to ElectWin!',
    enteredAsAdmin: 'Logged in to ElectWin as Super Admin (Demo Mode)',
    accountCreated: 'Account created successfully. Please log in with your credentials.',
    invalidCredentials: 'Invalid email or password.',
    backendNotRunning: 'Demo login failed — make sure the backend is running on port 8000.',
    signUpFailed: 'Sign up failed.',
    // Common actions
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    submit: 'Submit',
    back: 'Back',
    next: 'Next',
    // Table actions
    action: 'Action',
    status: 'Status',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    date: 'Date',
    // Dashboard specific
    totalVotersReachable: 'Total Voters (Reachable)',
    broadcastsDispatched: 'Broadcasts Sent',
    successRate: 'Success Rate',
    teamMembersCount: 'Team Members',
    // Navigation items
    navigationSidebarCampaignMgmt: 'Campaign Management',
    navigationSidebarFieldVolunteer: 'Field Volunteer Desk',
    navItemDashboard: 'Dashboard',
    navItemTeam: 'Team',
    navItemCandidates: 'Candidates',
    navItemVoters: 'Voters',
    navItemDesignStudio: 'Design Studio',
    navItemBroadcast: 'Broadcast',
    navItemVolunteers: 'Volunteers',
    navItemComplaints: 'Complaints',
    navItemExpenses: 'Expenses',
    navItemAnalytics: 'Analytics',
    navItemSettings: 'Settings',
    navItemWardFieldDesk: 'Ward Desk',
    navItemAddVoter: 'Add Voter',
    navItemFieldRecord: 'My Records',
    navItemSignOut: 'Sign Out',
    mobileNavDashboard: 'Dashboard',
    mobileNavVoters: 'Voters',
    mobileNavStudio: 'Studio',
    mobileNavBroadcast: 'Broadcast',
    mobileNavFieldDesk: 'Field Desk',
    navbarToggleSidebar: 'Toggle Navigation',
    navbarChangeLanguage: 'Change Language',
    navbarNotifications: 'Notifications',
    all: 'All',
    submitBy: 'Submitted by',
    // Task Management
    navItemTasks: 'Tasks',
    taskManagement: 'Task Management',
    myTasks: 'My Tasks',
    createTask: 'Create Task',
    taskTitle: 'Task Title',
    taskDescription: 'Task Description',
    taskPriority: 'Priority',
    taskDeadline: 'Deadline',
    assignToVolunteer: 'Assign to Volunteer',
    taskStatus: 'Status',
    taskPending: 'Pending',
    taskInProgress: 'In Progress',
    taskCompleted: 'Completed',
    taskCreated: 'Task created successfully',
    taskUpdated: 'Task updated successfully',
    noTasksYet: 'No tasks yet',
    noTasksDescription: 'Create your first task to get started',
    taskAssigned: 'Task assigned to you',
    // Field Activity
    navItemFieldActivities: 'Field Activities',
    fieldActivityReport: 'Field Activity Report',
    submitActivity: 'Submit Activity',
    activityType: 'Activity Type',
    activityLocation: 'Location',
    activityDateTime: 'Date & Time',
    activityDescription: 'Activity Description',
    activityPhotos: 'Photos/Documents',
    activityStatus: 'Status',
    activitySubmitted: 'Activity submitted successfully',
    activityReview: 'Activity Review',
    noActivitiesYet: 'No activities submitted',
    // Reports
    reportsAnalytics: 'Reports',
    volunteerPerformance: 'Volunteer Performance',
    performanceMetrics: 'Performance Metrics',
    taskCompletionRate: 'Task Completion %',
    attendanceSummary: 'Attendance Summary',
    exportPDF: 'Export PDF',
    exportExcel: 'Export Excel',
    // Billing & Subscription
    billingSubscription: 'Billing & Subscription',
    subscriptionPlan: 'Subscription Plan',
    planBasic: 'Basic',
    planProfessional: 'Professional',
    planEnterprise: 'Enterprise',
    planPrice: '₹{price}/month',
    planFeatures: 'Features Included',
    selectPlan: 'Select Plan',
    comingSoon: 'Coming Soon',
    planBasicFeatures: 'Up to 100 voters, Basic analytics, Email support',
    planProFeatures: 'Up to 10,000 voters, Advanced analytics, Priority support',
    planEnterpriseFeatures: 'Unlimited voters, Custom features, Dedicated support',
    // Password Reset
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    enterEmail: 'Enter your email address',
    sendReset: 'Send Reset Link',
    resetSent: 'Password reset link sent to your email',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    passwordReset: 'Password Reset',
    // Notification Types
    notificationTaskDeadline: 'Task deadline approaching'
  },
  hi: {
    commandCenter: 'चुनाव अभियान वॉर रूम',
    commandCenterSub: 'ग्राम पंचायत रामपुर चुनाव के लिए ग्राउंड स्तर का लाइव डेटा।',
    campaignTeam: 'अभियान टीम एवं अधिकार',
    teamDescription: 'प्रबंधक (Admin) और वार्ड पन्ना प्रमुख (Volunteer) जोड़ें एवं प्रबंधित करें।',
    candidateCenter: 'उम्मीदवार प्रबंधन केंद्र',
    candidateDescription: 'सरपंच एवं पंच प्रत्याशियों के प्रोफाइल, चुनाव चिह्न और घोषणापत्र।',
    voterDatabase: 'मतदाता सूची एवं संपर्क डेटाबेस',
    voterDatabaseDesc: 'आधिकारिक वोटर लिस्ट, CSV सिंक और कैमरा OCR वोटर पर्ची स्कैनर।',
    studioTitle: 'डिज़ाइन स्टूडियो एवं प्रचार सामग्री',
    studioSub: 'आधिकारिक चुनाव चिह्नों के साथ पोस्टर, फ्लेक्स बैनर एवं स्टेटस कार्ड बनाएं।',
    broadcastTitle: 'मैसेजिंग एवं ब्रॉडकास्ट सेंटर',
    broadcastSub: 'व्हाट्सएप एवं ऑटोमैटिक SMS फॉलबैक के साथ सीधे मतदाताओं तक संदेश।',
    boothOps: 'बूथ संचालन एवं पन्ना प्रमुख',
    surveysComplaints: 'जनसमस्याएं एवं शिकायतें',
    expensesLedger: 'चुनाव खर्च रजिस्टर',
    turnoutAnalytics: 'मतदान एवं रुझान विश्लेषण',
    settingsBranding: 'सेटिंग्स एवं ब्रांडिंग',
    totalVoters: 'कुल मतदाता',
    whatsappReached: 'व्हाट्सएप संपर्क',
    activeTeam: 'सक्रिय कार्यकर्ता',
    budgetUtilized: 'खर्च की गई राशि',
    searchVoters: 'मतदाता का नाम, मोबाइल नंबर या वार्ड खोजें...',
    allSegments: 'सभी मतदाता',
    exportCsv: 'CSV डाउनलोड',
    uploadRoll: 'लिस्ट अपलोड करें',
    scanOcr: 'वोटर पर्ची स्कैन (OCR)',
    addCandidate: '+ नया प्रत्याशी जोड़ें',
    addMember: '+ सदस्य जोड़ें',
    logGrievance: '+ समस्या दर्ज करें',
    addExpense: '+ नया खर्च जोड़ें',
    dispatchBroadcast: 'संदेश भेजें',
    dontHaveAccount: 'खाता नहीं है? साइन अप करें',
    alreadyAccount: 'पहले से खाता है? लॉगिन करें',
    continueDemo: 'डेमो मोड में आगे बढ़ें',
    roleSwitcher: 'भूमिका (Role) बदलें',
    dashboardOverview: 'डैशबोर्ड अवलोकन',
    currentElection: 'वर्तमान चुनाव',
    totalCandidatesOrganizations: 'कुल प्रत्याशी / संगठन',
    candidatesAndOrganizations: 'प्रत्याशी और संगठन',
    totalVotersAdded: 'जोड़े गए कुल मतदाता',
    liveVoterDatabase: 'लाइव मतदाता डेटाबेस',
    activeElections: 'सक्रिय चुनाव',
    electionPortfolio: 'चुनाव पोर्टफोलियो',
    recentActivity: 'हाल की गतिविधि',
    latestUpdates: 'नवीनतम अपडेट',
    last5Updates: 'अंतिम 5 अपडेट',
    type: 'प्रकार',
    details: 'विवरण',
    time: 'समय',
    totalVotersInElection: 'चुनाव में कुल मतदाता',
    volunteersCount: 'स्वयंसेवक',
    activeVolunteers: 'सक्रिय स्वयंसेवक',
    messagesSentThisWeek: 'इस सप्ताह भेजे गए संदेश',
    campaignReach: 'प्रचार पहुंच',
    wardCoverage: 'वार्ड-वार कवरेज',
    coverageSummary: 'कवरेज सारांश',
    quickActions: 'त्वरित कार्य',
    dailyChecklist: 'दैनिक चेकलिस्ट',
    addVoter: 'मतदाता जोड़ें',
    createPoster: 'पोस्टर बनाएं',
    sendBroadcast: 'ब्रॉडकास्ट भेजें',
    viewComplaints: 'शिकायतें देखें',
    wardVotersCount: 'वार्ड मतदाता',
    wardCoverageSummary: 'आपका वार्ड कवरेज',
    pendingTasks: 'लंबित कार्य',
    todayChecklist: 'आज की सूची',
    taskSummary: 'कार्य सारांश',
    assignedVoters: 'निर्यातित मतदाता',
    assignedVoterSummary: 'फॉलो-अप सूची',
    dashboardLoadError: 'बैकएंड से डेटा लोड नहीं हो सका',
    candidates: 'प्रत्याशी',
    organizations: 'संगठन',
    volunteers: 'स्वयंसेवक',
    recent: 'हालिया',
    // Auth Form
    createAccount: 'खाता बनाएं',
    signIn: 'साइन इन करें',
    registerVerifiedAccount: 'एक सत्यापित अभियान खाता पंजीकृत करें',
    enterCredentials: 'डैशबोर्ड तक पहुंचने के लिए अपने क्रेडेंशियल्स दर्ज करें',
    firstName: 'पहला नाम',
    enterFirstName: 'पहला नाम दर्ज करें',
    lastName: 'अंतिम नाम',
    enterLastName: 'अंतिम नाम दर्ज करें',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    createPassword: 'एक पासवर्ड बनाएं',
    enterPassword: 'अपना पासवर्ड दर्ज करें',
    authenticating: 'प्रमाणित कर रहे हैं...',
    creatingAccount: 'खाता बना रहे हैं...',
    or: 'या',
    alreadyHaveAccountLogin: 'पहले से खाता है? लॉगिन करें',
    quickDemoLogin: '🎯 त्वरित डेमो लॉगिन (सुपर एडमिन)',
    signUpNewAccount: 'एक नया खाता बनाने के लिए साइन अप करें',
    multiTenantNote: 'मल्टी-टेनेंट · JWT प्रमाणीकरण · भूमिका-आधारित RBAC',
    realTimeElection: 'रियल-टाइम चुनाव अभियान प्रबंधन',
    voterDataVolunteer: 'मतदाता डेटा · स्वयंसेवक प्रबंधन · डिजाइन स्टूडियो · स्मार्ट प्रसारण · विश्लेषण डैशबोर्ड',
    roleBasedAccess: 'भूमिका-आधारित पहुंच नियंत्रण (RBAC)',
    multiTenantOrg: 'मल्टी-टेनेंट संगठन अलगाव',
    realtimeDashboard: 'रियल-टाइम डैशबोर्ड और विश्लेषण',
    masterCampaignOS: '🇮🇳 आपका संपूर्ण चुनाव अभियान टूलकिट',
    // Form validation
    fieldRequired: 'यह फील्ड आवश्यक है',
    invalidEmail: 'कृपया एक वैध ईमेल दर्ज करें',
    passwordMismatch: 'पासवर्ड मेल नहीं खाते',
    // Role-based access
    selectRole: 'अपनी भूमिका चुनें',
    selectRoleForLogin: 'चुनें कि आप किस भूमिका से लॉगिन कर रहे हैं',
    selectRoleForSignup: 'चुनें कि आप किस भूमिका के रूप में साइन अप कर रहे हैं',
    roleSuperAdmin: 'सुपर एडमिन',
    roleAdmin: 'एडमिन (उम्मीदवार)',
    roleVolunteer: 'स्वयंसेवक',
    roleSuperAdminDesc: 'संपूर्ण सिस्टम पहुंच और संगठन प्रबंधन',
    roleAdminDesc: 'उम्मीदवार और अभियान प्रबंधन',
    roleVolunteerDesc: 'क्षेत्र गतिविधियों और मतदाता आउटरीच',
    inviteOnlySignup: 'केवल आमंत्रण से साइन अप',
    contactAdminSignup: 'नए खाते आपके एडमिन द्वारा बनाए जाते हैं। साइन अप करने के लिए उनसे संपर्क करें।',
    superAdminExists: 'सुपर एडमिन खाता पहले से मौजूद है। सार्वजनिक साइन अप अक्षम है।',
    selectRoleToSignup: 'जारी रखने के लिए अपनी भूमिका चुनें (केवल सुपर एडमिन नए खातों के लिए उपलब्ध)',
    currentRole: 'वर्तमान भूमिका',
    // Success/Error messages
    welcomeMessage: 'ElectWin वॉर रूम में आपका स्वागत है!',
    enteredAsAdmin: 'ElectWin में सुपर एडमिन के रूप में प्रवेश किया (डेमो मोड)',
    accountCreated: 'खाता बनाया गया। कृपया अपने क्रेडेंशियल्स के साथ लॉगिन करें।',
    invalidCredentials: 'अमान्य ईमेल या पासवर्ड।',
    backendNotRunning: 'डेमो लॉगिन विफल — सुनिश्चित करें कि बैकएंड पोर्ट 8000 पर चल रहा है।',
    signUpFailed: 'साइन अप विफल।',
    // Common actions
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    close: 'बंद करें',
    submit: 'जमा करें',
    back: 'पीछे',
    next: 'अगला',
    // Table actions
    action: 'कार्रवाई',
    status: 'स्थिति',
    name: 'नाम',
    email: 'ईमेल',
    phone: 'फोन',
    date: 'तारीख',
    // Dashboard specific
    totalVotersReachable: 'कुल मतदाता (पहुंचने योग्य)',
    broadcastsDispatched: 'प्रसारण भेजे गए',
    successRate: 'सफलता दर',
    teamMembersCount: 'टीम सदस्यों की संख्या',
    // Navigation items
    navigationSidebarCampaignMgmt: 'प्रचार प्रबंधन',
    navigationSidebarFieldVolunteer: 'क्षेत्र स्वयंसेवक डेस्क',
    navItemDashboard: 'डैशबोर्ड',
    navItemTeam: 'टीम',
    navItemCandidates: 'प्रत्याशी',
    navItemVoters: 'मतदाता',
    navItemDesignStudio: 'डिज़ाइन स्टूडियो',
    navItemBroadcast: 'प्रसारण',
    navItemVolunteers: 'स्वयंसेवक',
    navItemComplaints: 'शिकायतें',
    navItemExpenses: 'खर्च',
    navItemAnalytics: 'विश्लेषण',
    navItemSettings: 'सेटिंग्स',
    navItemWardFieldDesk: 'वार्ड डेस्क',
    navItemAddVoter: 'मतदाता जोड़ें',
    navItemFieldRecord: 'मेरे रिकॉर्ड',
    navItemSignOut: 'साइन आउट',
    mobileNavDashboard: 'डैशबोर्ड',
    mobileNavVoters: 'मतदाता',
    mobileNavStudio: 'स्टूडियो',
    mobileNavBroadcast: 'प्रसारण',
    mobileNavFieldDesk: 'क्षेत्र डेस्क',
    navbarToggleSidebar: 'नेविगेशन टॉगल',
    navbarChangeLanguage: 'भाषा बदलें',
    navbarNotifications: 'सूचनाएं',
    // Professional Copy - Candidates Page
    filterAllCandidates: 'सभी प्रत्याशी',
    filterSarpanch: 'सरपंच',
    filterPanch: 'वार्ड सदस्य',
    emptyCandidatesTitle: 'अभी कोई प्रत्याशी नहीं',
    emptyCandidatesDesc: 'अपने पहले प्रत्याशी को जोड़कर शुरुआत करें — उनका प्रोफाइल, चुनाव चिह्न और अभियान संदेश यहाँ दिखाई देगा।',
    candidateAddedSuccess: 'प्रत्याशी प्रोफाइल सफलतापूर्वक बनाया गया!',
    candidateDeletedSuccess: 'प्रत्याशी को अभियान से हटा दिया गया।',
    candidatePhoto: 'प्रत्याशी की फोटो',
    uploadPhotoTitle: 'प्रत्याशी की फोटो अपलोड करें',
    candidateSymbol: 'चुनाव चिह्न',
    symbolLabel: 'चिह्न का नाम',
    sloganLabel: 'अभियान का नारा',
    manifestoLabel: 'चुनाव घोषणापत्र और वादे',
    // Professional Copy - Voters Page
    filterAllVoters: 'सभी मतदाता',
    filterHasWhatsApp: 'WhatsApp के साथ',
    filterNoWhatsApp: 'केवल SMS',
    filterYouth: 'युवा (18-35)',
    filterWomen: 'महिलाएं',
    filterMissingContact: 'संपर्क सूचना नहीं',
    emptyVotersTitle: 'अपनी मतदाता सूची बनाएं',
    emptyVotersDesc: 'अपनी आधिकारिक मतदाता सूची अपलोड करें या मतदाताओं को एक-एक करके जोड़ें। आयात के बाद वे यहाँ दिखाई देंगे।',
    uploadVotersList: 'मतदाता सूची अपलोड करें',
    importFromCSV: 'CSV / PDF सूची आयात करें',
    addVoterManually: 'एक मतदाता जोड़ें',
    startOCRScanner: 'मतदाता पर्ची स्कैन करें (कैमरा)',
    ocrScannerTitle: 'मतदाता पर्ची स्कैनर',
    ocrScannerDesc: 'आधिकारिक मतदाता पर्ची की फोटो लें — ElectWin स्वचालित रूप से नाम, ID, मोबाइल और पता निकालेगा।',
    ocrProcessing: 'मतदाता पर्ची स्कैन कर रहा है... डेटा निकाल रहा है...',
    ocrSuccess: 'स्कैन किया गया और तैयार! सहेजने से पहले निकाले गए डेटा की समीक्षा करें।',
    voterAddedSuccess: 'मतदाता को अभियान डेटाबेस में सफलतापूर्वक जोड़ा गया!',
    voterImportSuccess: '{{count}} मतदाता आपकी फ़ाइल से आयात किए गए — अंतिम रूप देने से पहले समीक्षा करें और पुष्टि करें।',
    voterMobileValidation: 'मोबाइल नंबर 10 अंकों का होना चाहिए (उदा. 98290 14285)',
    voterNameRequired: 'मतदाता का नाम आवश्यक है',
    voterListDownload: 'मतदाता सूची डाउनलोड करें (CSV)',
    // Professional Copy - Broadcast Page
    broadcastDraftTitle: 'संदेश टेम्पलेट',
    broadcastDraftDesc: 'अपना अभियान संदेश लिखें। प्रत्येक मतदाता के लिए व्यक्तिगत करने के लिए {{tags}} का उपयोग करें ({{name}}, {{ward}}, {{symbol}})।',
    broadcastWithPoster: 'अभियान पोस्टर शामिल करें',
    broadcastWithPosterDesc: 'अधिकतम दृश्य प्रभाव के लिए WhatsApp संदेशों में एक उच्च-गुणवत्ता वाली पोस्टर छवि जोड़ें।',
    broadcastReady: 'भेजने के लिए तैयार',
    broadcastPreview: 'संदेश पूर्वावलोकन (मतदाता क्या देखते हैं)',
    broadcastSendTo: 'डिलीवरी लक्ष्य',
    broadcastAllWards: 'सभी वार्ड',
    broadcastSelectWards: 'विशिष्ट वार्ड चुनें',
    broadcastChannelDual: 'स्मार्ट ड्यूल पाइपलाइन: WhatsApp → SMS फॉलबैक',
    broadcastWhatsAppPrimary: 'प्राथमिक चैनल (WhatsApp)',
    broadcastSMSFallback: 'SMS फॉलबैक रूट',
    broadcastRichMedia: 'रिच मीडिया + नीली टिक',
    broadcastBasicText: 'केवल पाठ',
    broadcastSendNow: 'अभी प्रसारण भेजें',
    broadcastSchedule: 'बाद में शेड्यूल करें',
    broadcastSending: '{{count}} मतदाताओं को भेज रहा है...',
    broadcastSentSuccess: 'प्रसारण भेज दिया गया! कुछ मिनटों में डिलीवरी रिपोर्ट आएगी।',
    broadcastSentFailed: 'प्रसारण भेजना विफल — अपने संदेश की जांच करें और फिर से प्रयास करें।',
    broadcastEmptyTitle: 'अभी तक कोई संदेश नहीं भेजा गया',
    broadcastEmptyDesc: 'सभी वार्डों में मतदाताओं तक पहुंचने के लिए अपना पहला अभियान संदेश लिखें और भेजें।',
    deliveryReportTitle: 'डिलीवरी रिपोर्ट',
    deliveryReportDesc: 'सभी मतदाताओं में संदेश स्थिति का रीयल-टाइम ट्रैकिंग।',
    deliveryStatus: 'स्थिति',
    deliveryDelivered: 'डिलीवर किया गया',
    deliveryRead: 'पढ़ा गया',
    deliveryFailed: 'विफल',
    deliveryPending: 'अनिर्णीत',
    // Professional Copy - Design Studio
    studioBlankCanvas: 'एक खाली कैनवास से शुरुआत करें',
    studioBlankDesc: 'पोस्टर, बैनर या स्टेटस कार्ड से चुनें — रंग, फोटो और पाठ के साथ अनुकूलित करें।',
    studioTemplateTitle: 'एक अभियान टेम्पलेट चुनें',
    studioTemplateDesc: 'प्रमाणित डिज़ाइन से चुनें — चुनाव पोस्टर, वार्ड घोषणाएं या प्रचार बैनर।',
    studioPhotoTitle: 'अभियान फोटो अपलोड करें',
    studioPhotoDesc: 'एक पेशेदार प्रत्याशी फोटो, पार्टी चिह्न या वार्ड लोगो जोड़ें।',
    studioDownloadPDF: 'PDF के रूप में डाउनलोड करें',
    studioDownloadImage: 'छवि के रूप में डाउनलोड करें',
    studioShareTemplate: 'अभियान संपत्ति साझा करें',
    studioDesignSaved: 'अभियान डिज़ाइन गैलरी में सहेजा गया!',
    studioEmptyTitle: 'अभियान गैलरी',
    studioEmptyDesc: 'यहाँ पोस्टर, बैनर और स्टेटस कार्ड बनाएं — फिर डाउनलोड करें और अपनी टीम के साथ साझा करें।',
    // Professional Copy - Complaints Page
    complaintStatusPending: 'कार्रवाई की प्रतीक्षा में',
    complaintStatusInProgress: 'समीक्षा में',
    complaintStatusResolved: 'समाधान',
    emptyComplaintsTitle: 'अभी तक कोई शिकायत नहीं',
    emptyComplaintsDesc: 'मतदाता अपने संपर्क चैनलों के माध्यम से शिकायतें दर्ज कर सकते हैं — वे यहाँ कार्रवाई के लिए दिखाई देंगी।',
    complaintCategory: 'श्रेणी',
    complaintPriority: 'प्राथमिकता',
    complaintMarkResolved: 'समाधित के रूप में चिह्नित करें',
    complaintAddedSuccess: 'शिकायत दर्ज की गई और आपकी टीम को सौंपी गई।',
    complaintResolvedSuccess: 'शिकायत समाधित के रूप में चिह्नित — मतदाता के साथ फॉलो-अप करें।',
    // Professional Copy - Expenses Page
    expensesTitle: 'अभियान बजट और खर्च',
    expensesDesc: 'अभियान गतिविधियों पर खर्च किए गए हर रुपये को ट्रैक करें — सीमा के भीतर रहें और पूर्ण पारदर्शिता बनाए रखें।',
    expenseCategoryFood: 'भोजन और कैटरिंग',
    expenseCategoryTransport: 'परिवहन और यात्रा',
    expenseCategoryMaterial: 'छपाई सामग्री',
    expenseCategoryMedia: 'मीडिया और विज्ञापन',
    expenseCategoryOther: 'अन्य खर्च',
    expenseAddTitle: 'एक नया खर्च दर्ज करें',
    expenseAmount: 'राशि (₹)',
    expenseVendor: 'विक्रेता / आपूर्तिकर्ता का नाम',
    expenseNotes: 'विवरण (वैकल्पिक)',
    expenseReceipt: 'रसीद अपलोड करें (फोटो)',
    expenseAddedSuccess: 'खर्च दर्ज किया गया — बजट स्वचालित रूप से अपडेट किया गया।',
    emptyExpensesTitle: 'अपने अभियान खर्च को ट्रैक करें',
    emptyExpensesDesc: 'पारदर्शिता बनाए रखने के लिए यहाँ खर्च दर्ज करें और सुनिश्चित करें कि आप अपने आवंटित बजट के भीतर रहें।',
    totalSpent: 'कुल खर्च',
    budgetRemaining: 'बजट बचा हुआ',
    // Professional Copy - Analytics Page
    analyticsTitle: 'अभियान प्रदर्शन और अंतर्दृष्टि',
    analyticsDesc: 'मतदाता पहुंच, सगाई दर और मतदान प्रवृत्तियों पर रीयल-टाइम डैशबोर्ड।',
    turnoutLabel: 'मतदान',
    engagementLabel: 'संदेश सगाई',
    deliveryRateLabel: 'डिलीवरी सफलता दर',
    contactReachLabel: 'पहुंचने योग्य मतदाता',
    emptyAnalyticsTitle: 'अभी तक कोई डेटा नहीं',
    emptyAnalyticsDesc: 'एक बार जब आप प्रसारण भेजते हैं और अभियान शुरू होते हैं तो विश्लेषण यहाँ दिखाई देगा।',
    // Professional Copy - Volunteers Page
    emptyVolunteersTitle: 'बूथ टीम रोस्टर',
    emptyVolunteersDesc: 'वार्डों और पन्ना अनुभागों में स्वयंसेवकों को असाइन करें — अपनी जमीनी टीम को कुशलता से प्रबंधित करें।',
    volunteerRole: 'भूमिका',
    volunteerWard: 'निर्यातित वार्ड',
    volunteerSections: 'पन्ना अनुभाग',
    volunteerPhone: 'संपर्क नंबर',
    volunteerAddNew: 'एक नया स्वयंसेवक जोड़ें',
    volunteerAddedSuccess: 'स्वयंसेवक आपकी अभियान टीम में जोड़ा गया!',
    volunteerDeletedSuccess: 'स्वयंसेवक को टीम से हटा दिया गया।',
    // Professional Copy - Settings Page
    settingsTitle: 'अभियान सेटिंग्स और ब्रांडिंग',
    settingsDesc: 'अपने अभियान थीम को अनुकूलित करें, उपयोगकर्ता खातों को प्रबंधित करें और सूचनाएं कॉन्फ़िगर करें।',
    campaignName: 'अभियान का नाम',
    campaignColor: 'अभियान रंग थीम',
    campaignColorDesc: 'सभी अभियान सामग्री के लिए प्राथमिक रंग चुनें।',
    partySymbol: 'पार्टी चिह्न',
    uploadLogo: 'पार्टी लोगो अपलोड करें',
    notificationSettings: 'अधिसूचना प्राथमिकताएं',
    enableEmailNotif: 'ईमेल सूचनाएं',
    enableSMSNotif: 'SMS अलर्ट',
    settingsSavedSuccess: 'अभियान सेटिंग्स अपडेट की गई!',
    // Professional Copy - General Actions
    addNew: 'जोड़ें',
    editItem: 'संपादित करें',
    deleteItem: 'हटाएं',
    confirmDelete: 'क्या आप सुनिश्चित हैं? यह कार्रवाई पूर्ववत नहीं की जा सकती।',
    yesDelete: 'हाँ, हटाएं',
    noCancel: 'रद्द करें',
    searchPlaceholder: 'यहाँ खोजें...',
    noResultsFound: 'कोई परिणाम नहीं मिले — एक अलग खोज शब्द आजमाएं।',
    loadingData: 'डेटा लोड हो रहा है...',
    savingChanges: 'परिवर्तन सहेज रहा है...',
    errorLoadingData: 'डेटा लोड नहीं कर सके — अपने कनेक्शन की जांच करें और फिर से प्रयास करें।',
    errorSavingData: 'सहेजना विफल — कृपया फिर से प्रयास करें।',
    tryAgain: 'फिर से प्रयास करें',
    returnToDashboard: 'डैशबोर्ड पर वापस जाएं',
    // Error & Success Messages for Forms and Uploads
    failedLoadingAnalytics: 'विश्लेषण डेटा लोड करने में विफल',
    analyticsReportExported: 'विश्लेषण रिपोर्ट निर्यात की गई!',
    failedLoadingComplaints: 'शिकायतें लोड करने में विफल',
    grievanceRegistered: 'नागरिक शिकायत सफलतापूर्वक दर्ज की गई!',
    photoUploadedSuccessfully: 'फोटो सफलतापूर्वक अपलोड की गई',
    photoUploadFailed: 'फोटो अपलोड करने में विफल',
    symbolUploadedSuccessfully: 'प्रतीक सफलतापूर्वक अपलोड किया गया',
    symbolUploadFailed: 'प्रतीक अपलोड करने में विफल',
    candidateNameRequired: 'प्रत्याशी का नाम आवश्यक है',
    positionRequired: 'पद आवश्यक है',
    wardNumberRequired: 'वार्ड संख्या आवश्यक है',
    candidatePhotoRequired: 'कृपया प्रत्याशी की फोटो अपलोड करें',
    canvasNotReady: 'कैनवास तैयार नहीं है',
    posterDownloadedSuccessfully: 'पोस्टर सफलतापूर्वक डाउनलोड किया गया!',
    posterDownloadFailed: 'पोस्टर डाउनलोड करने में विफल',
    failedLoadingExpenses: 'खर्च लोड करने में विफल',
    failedLoadingTeamMembers: 'टीम सदस्यों को लोड करने में विफल',
    notAuthorizedAddRole: 'आप इस भूमिका को जोड़ने के लिए अधिकृत नहीं हैं।',
    noPermissionRemoveRole: 'आपके पास इस भूमिका को हटाने की अनुमति नहीं है।',
    selectActiveElectionBeforeAdding: 'मतदाता जोड़ने से पहले सक्रिय चुनाव चुनें।',
    failedLoadingVoters: 'बैकएंड से मतदाता लोड करने में विफल',
    noActiveElectionSelected: 'कोई सक्रिय चुनाव नहीं चुना गया',
    officialVoterListDownloaded: 'आधिकारिक मतदाता सूची CSV डाउनलोड की गई!',
    allCampaignSettingsSaved: '✅ सभी प्रचार सेटिंग्स सफलतापूर्वक सहेजी गईं! रंग और थीम सहेजी गई।',
    emblemLogoUploadedSuccessfully: 'प्रतीक लोगो सफलतापूर्वक अपलोड किया गया!',
    fillAllRequiredFields: 'कृपया सभी आवश्यक फील्ड भरें',
    teamMembersPageTitle: 'टीम सदस्य',
    addCampaignTeamMember: 'अभियान टीम सदस्य जोड़ें',
    // Form Labels
    formLabelFirstName: 'पहला नाम',
    formLabelLastName: 'अंतिम नाम',
    formLabelEmail: 'ईमेल',
    formLabelPassword: 'पासवर्ड',
    formLabelPhoneNumber: 'फोन नंबर',
    formLabelWardName: 'वार्ड / क्षेत्र असाइनमेंट',
    formLabelRoleHierarchy: 'भूमिका पदानुक्रम',
    formPlaceholderFirstName: 'उदा. रमेश',
    formPlaceholderLastName: 'उदा. साइनी',
    formPlaceholderEmail: 'उदा. member@electwin.com',
    formPlaceholderPassword: 'एक पासवर्ड बनाएं',
    formPlaceholderPhoneNumber: '+91 98765 43210',
    phoneExample: '9876543210',
    emailExample: 'superadmin@electwin.com',
    otpContactExample: 'name@electwin.com या 9876543210',
    notificationTaskAssigned: 'नया कार्य सौंपा गया',
    notificationDeadlineApproaching: 'समय सीमा निकट है',
    notificationActivitySubmitted: 'गतिविधि समीक्षा के लिए प्रस्तुत की गई',
    notificationMarkAsRead: 'पढ़ा हुआ चिह्नित करें',
    notificationDelete: 'सूचना हटाएं',
    notificationClearAll: 'सभी सूचनाएं साफ करें',
    notificationNoNotifications: 'कोई सूचना नहीं',
    notificationAllCaughtUp: 'आप सब कुछ देख चुके हैं!',
    notificationUnread: 'अपठित',
    notificationJustNow: 'अभी अभी',
    memberFilterAll: 'सभी',
    memberFilterAdmins: 'एडमिन',
    memberFilterVolunteers: 'स्वयंसेवक',
    memberSearchPlaceholder: 'नाम, वार्ड या भूमिका से टीम सदस्य खोजें...',
    memberAssignedWard: 'निर्यातित वार्ड',
    memberVotersHandled: 'देखे गए मतदाता',
    memberAddedDate: 'जोड़ने की तिथि',
    memberActiveStatus: 'सक्रिय',
    memberInactiveStatus: 'निष्क्रिय',
    memberEditAction: 'संपादित करें',
    memberRemoveAction: 'हटाएं',
    memberSave: 'सदस्य सहेजें',
    memberLoading: 'लोड हो रहा है...',
    memberAdd: 'सदस्य जोड़ें',
    memberCountLabel: 'सदस्य',
    memberFilterLabel: 'सभी',
    memberElectorsLabel: 'मतदाता',
    roleAdminCampaignManager: 'एडमिन (कैम्पेन मैनेजर)',
    roleVolunteerFieldWorker: 'स्वयंसेवक (फील्ड वर्कर)',
    wardAllCampaignHQ: 'सभी वार्ड (कैम्पेन एचक्यू)',
    teamMemberAddedSuccessPrefix: 'टीम सदस्य',
    teamMemberAddedSuccessSuffix: 'सफलतापूर्वक जोड़ दिया गया!',
    teamMemberEditReadyPrefix: 'संपादन प्रवाह',
    teamMemberEditReadySuffix: 'अगली बैकएंड इंटीग्रेशन के लिए तैयार है।',
    teamMemberRemovePrefix: 'हटाने की प्रक्रिया भूमिका अनुमति द्वारा नियंत्रित है और बैकएंड स्तर पर लागू की जाएगी।',
    notificationMinutesAgo: '{count}m पहले',
    notificationHoursAgo: '{count}h पहले',
    notificationDaysAgo: '{count}d पहले',
    all: 'सभी',
    submitBy: 'द्वारा जमा किया गया',
    navItemFieldActivities: 'क्षेत्र गतिविधियां',
    navItemTasks: 'कार्य'
  },
  pa: {
    commandCenter: 'ਚੋਣ ਮੁਹਿੰਮ ਕਮਾਂਡ ਸੈਂਟਰ',
    commandCenterSub: 'ਗ੍ਰਾਮ ਪੰਚਾਇਤ ਰਾਮਪੁਰ ਚੋਣਾਂ ਦਾ ਲਾਈਵ ਡਾਟਾ।',
    campaignTeam: 'ਮੁਹਿੰਮ ਟੀਮ ਅਤੇ ਅਧਿਕਾਰ',
    teamDescription: 'ਪ੍ਰਬੰਧਕ ਅਤੇ ਵਾਰਡ ਬੂਥ ਇੰਚਾਰਜ ਸ਼ਾਮਲ ਕਰੋ।',
    candidateCenter: 'ਉਮੀਦਵਾਰ ਪ੍ਰਬੰਧਨ ਕੇਂਦਰ',
    candidateDescription: 'ਚੋਣ ਨਿਸ਼ਾਨ ਅਤੇ ਮੈਨੀਫੈਸਟੋ ਪ੍ਰਬੰਧਨ।',
    voterDatabase: 'ਵੋਟਰ ਸੂਚੀ ਅਤੇ ਡਾਟਾਬੇਸ',
    voterDatabaseDesc: 'ਸਰਕਾਰੀ ਵੋਟਰ ਸੂਚੀ ਅਤੇ ਕੈਮਰਾ OCR ਸਕੈਨਰ।',
    studioTitle: 'ਡਿਜ਼ਾਈਨ ਸਟੂਡੀਓ',
    studioSub: 'ਪੋਸਟਰ, ਫਲੈਕਸ ਬੈਨਰ ਅਤੇ ਵਟਸਐਪ ਕਾਰਡ ਬਣਾਓ।',
    broadcastTitle: 'ਸੁਨੇਹਾ ਕੇਂਦਰ',
    broadcastSub: 'ਵਟਸਐਪ ਅਤੇ SMS ਸੁਨੇਹੇ ਭੇਜੋ।',
    boothOps: 'ਬੂਥ ਸੰਚਾਲਨ',
    surveysComplaints: 'ਸ਼ਿਕਾਇਤਾਂ ਅਤੇ ਮੁੱਦੇ',
    expensesLedger: 'ਖਰਚਾ ਰਜਿਸਟਰ',
    turnoutAnalytics: 'ਵੋਟਿੰਗ ਵਿਸ਼ਲੇਸ਼ਣ',
    settingsBranding: 'ਸੈਟਿੰਗਾਂ',
    totalVoters: 'ਕੁੱਲ ਵੋਟਰ',
    whatsappReached: 'ਵਟਸਐਪ ਪਹੁੰਚ',
    activeTeam: 'ਸਰਗਰਮ ਟੀਮ',
    budgetUtilized: 'ਖਰਚਿਆ ਬਜਟ',
    searchVoters: 'ਵੋਟਰ ਲੱਭੋ...',
    allSegments: 'ਸਾਰੇ ਵੋਟਰ',
    exportCsv: 'CSV ਡਾਊਨਲੋਡ',
    uploadRoll: 'ਫਾਈਲ ਅੱਪਲੋਡ',
    scanOcr: 'OCR ਸਕੈਨ',
    addCandidate: '+ ਉਮੀਦਵਾਰ ਸ਼ਾਮਲ ਕਰੋ',
    addMember: '+ ਮੈਂਬਰ ਸ਼ਾਮਲ ਕਰੋ',
    logGrievance: '+ ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
    addExpense: '+ ਖਰਚ ਸ਼ਾਮਲ ਕਰੋ',
    dispatchBroadcast: 'ਸੁਨੇਹਾ ਭੇਜੋ',
    dontHaveAccount: 'ਖਾਤਾ ਨਹੀਂ ਹੈ? ਸਾਈਨ ਅੱਪ ਕਰੋ',
    alreadyAccount: 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ? ਲੌਗਇਨ ਕਰੋ',
    continueDemo: 'ਬਿਨਾਂ ਲੌਗਇਨ ਅੱਗੇ ਵਧੋ',
    roleSwitcher: 'ਰੋਲ ਬਦਲੋ',
    dashboardOverview: 'ਡੈਸ਼ਬੋਰਡ ਓਵਰਵਿਊ',
    currentElection: 'ਮੌਜੂਦਾ ਚੋਣ',
    totalCandidatesOrganizations: 'ਕੁੱਲ ਉਮੀਦਵਾਰ / ਸੰਸਥਾਵਾਂ',
    candidatesAndOrganizations: 'ਉਮੀਦਵਾਰ ਅਤੇ ਸੰਸਥਾਵਾਂ',
    totalVotersAdded: 'ਜੋੜੇ ਗਏ ਕੁੱਲ ਵੋਟਰ',
    liveVoterDatabase: 'ਲਾਈਵ ਵੋਟਰ ਡਾਟਾਬੇਸ',
    activeElections: 'ਸਕਰਿਵ ਚੋਣਾਂ',
    electionPortfolio: 'ਚੋਣ ਪੋਰਟਫੋਲਿਓ',
    recentActivity: 'ਤਾਜ਼ਾ ਗਤੀਵਿਧੀ',
    latestUpdates: 'ਨਵੀਆਂ ਅਪਡੇਟਸ',
    last5Updates: 'ਆਖਰੀ 5 ਅਪਡੇਟਸ',
    type: 'ਕਿਸਮ',
    details: 'ਵੇਰਵਾ',
    time: 'ਸਮਾਂ',
    totalVotersInElection: 'ਚੋਣ ਵਿੱਚ ਕੁੱਲ ਵੋਟਰ',
    volunteersCount: 'ਵਾਲੰਟੀਅਰ',
    activeVolunteers: 'ਸਕਰਿਵ ਵਾਲੰਟੀਅਰ',
    messagesSentThisWeek: 'ਇਸ ਹਫਤੇ ਭੇਜੇ ਗਏ ਸੁਨੇਹੇ',
    campaignReach: 'ਪ੍ਰਚਾਰ ਪਹੁੰਚ',
    wardCoverage: 'ਵਾਰਡ-ਵਾਰ ਕਵਰੇਜ',
    coverageSummary: 'ਕਵਰੇਜ ਸਾਰ',
    quickActions: 'ਤੁਰੰਤ ਕਾਰਵਾਈ',
    dailyChecklist: 'ਰੋਜ਼ਾਨਾ ਚੈਕਲਿਸਟ',
    addVoter: 'ਵੋਟਰ ਜੋੜੋ',
    createPoster: 'ਪੋਸਟਰ ਬਣਾਓ',
    sendBroadcast: 'ਬ੍ਰਾਡਕਾਸਟ ਭੇਜੋ',
    viewComplaints: 'ਸ਼ਿਕਾਇਤਾਂ ਦੇਖੋ',
    wardVotersCount: 'ਵਾਰਡ ਵੋਟਰ',
    wardCoverageSummary: 'ਤੁਹਾਡਾ ਵਾਰਡ ਕਵਰੇਜ',
    pendingTasks: 'ਬਕਾਇਆ ਕੰਮ',
    todayChecklist: 'ਅੱਜ ਦੀ ਚੈਕਲਿਸਟ',
    taskSummary: 'ਕੰਮ ਸਾਰ',
    assignedVoters: 'ਨਿਰਧਾਰਤ ਵੋਟਰ',
    assignedVoterSummary: 'ਫੋਲੋ-ਅਪ ਸੂਚੀ',
    dashboardLoadError: 'ਬੈਕਐਂਡ ਤੋਂ ਡੇਟਾ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕਿਆ',
    candidates: 'ਉਮੀਦਵਾਰ',
    organizations: 'ਸੰਸਥਾਵਾਂ',
    volunteers: 'ਵਾਲੰਟੀਅਰ',
    recent: 'ਤਾਜ਼ਾ',
    // Auth Form
    createAccount: 'ਖਾਤਾ ਬਣਾਓ',
    signIn: 'ਸਾਈਨ ਇਨ',
    registerVerifiedAccount: 'ਪ੍ਰਮਾਣਿਤ ਮੁਹਿੰਮ ਖਾਤਾ ਰਜਿਸਟਰ ਕਰੋ',
    enterCredentials: 'ਡੈਸ਼ਬੋਰਡ ਤੱਕ ਪਹੁੰਚਣ ਲਈ ਆਪਣੀਆਂ ਪ੍ਰਮਾਣਿਤਤਾ ਦਰਜ ਕਰੋ',
    firstName: 'ਪਹਲਾ ਨਾਮ',
    enterFirstName: 'ਪਹਲਾ ਨਾਮ ਦਰਜ ਕਰੋ',
    lastName: 'ਆਖਰੀ ਨਾਮ',
    enterLastName: 'ਆਖਰੀ ਨਾਮ ਦਰਜ ਕਰੋ',
    emailAddress: 'ਈ-ਮੇਲ ਪਤਾ',
    password: 'ਪਾਸਵਰਡ',
    createPassword: 'ਪਾਸਵਰਡ ਬਣਾਓ',
    enterPassword: 'ਆਪਣਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
    authenticating: 'ਪ੍ਰਮਾਣਿਤ ਕਰ ਰਹੇ ਹਨ...',
    creatingAccount: 'ਖਾਤਾ ਬਣਾ ਰਹੇ ਹਨ...',
    or: 'ਜਾਂ',
    alreadyHaveAccountLogin: 'ਪਹਿਲਾਂ ਖਾਤਾ ਹੈ? ਲੌਗਇਨ ਕਰੋ',
    quickDemoLogin: '🎯 ਕਲਿਫ਼ ਡੇਮੋ ਲੌਗਇਨ (ਸੁਪਰ ਐਡਮਿਨ)',
    signUpNewAccount: 'ਨਵੇਂ ਖਾਤੇ ਲਈ ਸਾਈਨ ਅੱਪ ਕਰੋ',
    multiTenantNote: 'ਮਲਟੀ-ਟੇਨੈਂਟ · JWT ਪ੍ਰਮਾਣਿਕਤਾ · ਅਨੁਮਤੀ-ਆਧਾਰਿਤ RBAC',
    realTimeElection: 'ਰੀਅਲ-ਟਾਇਮ ਚੋਣ ਪ੍ਰਚਾਰ ਪ੍ਰਬੰਧਨ',
    voterDataVolunteer: 'ਵੋਟਰ ਡਾਟਾ · ਵਾਲੰਟੀਅਰ ਪ੍ਰਬੰਧਨ · ਡਿਜ਼ਾਈਨ ਸਟੂਡੀਓ · ਸਮਾਰਟ ਬ੍ਰਾਡਕਾਸਟ · ਵਿਸ਼ਲੇਸ਼ਣ ਡੈਸ਼ਬੋਰਡ',
    roleBasedAccess: 'ਭੂਮਿਕਾ-ਆਧਾਰਿਤ ਐਕਸੈਸ ਨਿਯੰਤਰਣ (RBAC)',
    multiTenantOrg: 'ਮਲਟੀ-ਟੇਨੈਂਟ ਸੰਸਥਾ ਨਿਰੋਧ',
    realtimeDashboard: 'ਰੀਅਲ-ਟਾਇਮ ਡੈਸ਼ਬੋਰਡ ਅਤੇ ਵਿਸ਼ਲੇਸ਼ਣ',
    masterCampaignOS: '🇮🇳 ਮਾਸਟਰ ਪ੍ਰਚਾਰ OS ਅਤੇ ਯੁੱਧ ਕਮਰਾ',
    // Form validation
    fieldRequired: 'ਇਹ ਖੇਤਰ ਲਾਜ਼ਮੀ ਹੈ',
    invalidEmail: 'ਕਿਰਪਾ ਇੱਕ ਵੈਲਿਡ ਈ-ਮੇਲ ਦਰਜ ਕਰੋ',
    passwordMismatch: 'ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ',
    // Success/Error messages
    welcomeMessage: 'ElectWin ਯੁੱਧ ਕਮਰੇ ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ!',
    enteredAsAdmin: 'ElectWin ਵਿੱਚ ਸੁਪਰ ਐਡਮਿਨ ਦੇ ਤੌਰ ਤੇ ਦਾਖਲ (ਡੇਮੋ ਮੋਡ)',
    accountCreated: 'ਖਾਤਾ ਬਣਾਇਆ ਗਿਆ। ਕਿਰਪਾ ਆਪਣੀਆਂ ਪ੍ਰਮਾਣਿਤਤਾ ਨਾਲ ਲੌਗਇਨ ਕਰੋ।',
    invalidCredentials: 'ਅਮਾਨਤ ਈ-ਮੇਲ ਜਾਂ ਪਾਸਵਰਡ।',
    backendNotRunning: 'ਡੇਮੋ ਲੌਗਇਨ ਅਸਫਲ — ਯਕੀਨੀ ਬਣਾਓ ਕਿ ਬੈਕਐਂਡ ਪੋਰਟ 8000 ਤੇ ਚਲ ਰਿਹਾ ਹੈ।',
    signUpFailed: 'ਸਾਈਨ ਅੱਪ ਅਸਫਲ।',
    // Common actions
    save: 'ਸਿਰਲੇਖ ਕਰੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    delete: 'ਹਟਾਓ',
    edit: 'ਸੰਪਾਦਿਤ ਕਰੋ',
    close: 'ਬੰਦ ਕਰੋ',
    submit: 'ਪੇਸ਼ ਕਰੋ',
    back: 'ਪਿੱਛੇ',
    next: 'ਅਗਲਾ',
    // Table actions
    action: 'ਕਾਰਵਾਈ',
    status: 'ਸਥਿਤੀ',
    name: 'ਨਾਮ',
    email: 'ਈ-ਮੇਲ',
    phone: 'ਫੋਨ',
    date: 'ਤਾਰੀਖ',
    // Dashboard specific
    totalVotersReachable: 'ਕੁਲ ਵੋਟਰ (ਪਹੁੰਚਿਆ ਜਾ ਸਕਦਾ ਹੈ)',
    broadcastsDispatched: 'ਪ੍ਰਸਾਰਣ ਭੇਜੇ ਗਏ',
    successRate: 'ਸਫਲਤਾ ਦਰ',
    teamMembersCount: 'ਟੀਮ ਸਦੱਸ ਦੀ ਗਿਣਤੀ',
    // Navigation items
    navigationSidebarCampaignMgmt: 'ਪ੍ਰਚਾਰ ਪ੍ਰਬੰਧਨ',
    navigationSidebarFieldVolunteer: 'ਖੇਤ ਵਾਲੰਟੀਅਰ ਡੇਸਕ',
    navItemDashboard: 'ਡੈਸ਼ਬੋਰਡ',
    navItemTeam: 'ਟੀਮ',
    navItemCandidates: 'ਉਮੀਦਵਾਰ',
    navItemVoters: 'ਵੋਟਰ',
    navItemDesignStudio: 'ਡਿਜ਼ਾਈਨ ਸਟੂਡੀਓ',
    navItemBroadcast: 'ਪ੍ਰਸਾਰਣ',
    navItemVolunteers: 'ਵਾਲੰਟੀਅਰ',
    navItemComplaints: 'ਸ਼ਿਕਾਇਤਾਂ',
    navItemExpenses: 'ਖਰਚਾ',
    navItemAnalytics: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    navItemSettings: 'ਸੈਟਿੰਗਾਂ',
    navItemWardFieldDesk: 'ਵਾਰਡ ਡੇਸਕ',
    navItemAddVoter: 'ਵੋਟਰ ਸ਼ਾਮਲ ਕਰੋ',
    navItemFieldRecord: 'ਮੇਰੇ ਰਿਕਾਰਡ',
    navItemSignOut: 'ਸਾਈਨ ਆਊਟ',
    mobileNavDashboard: 'ਡੈਸ਼ਬੋਰਡ',
    mobileNavVoters: 'ਮਤਦਾਤਾ',
    mobileNavStudio: 'ਸਟੂਡੀਓ',
    mobileNavBroadcast: 'ਪ੍ਰਸਾਰਣ',
    mobileNavFieldDesk: 'ਖੇਤ ਡੇਸਕ',
    navbarToggleSidebar: 'ਨਵੀਕਰਣ ਡ੍ਰਾਵਰ ਟਾਗਲ ਕਰੋ',
    navbarChangeLanguage: 'ਭਾਸ਼ਾ ਬਦਲੋ',
    navbarLiveNotifications: 'ਲਾਈਵ ਸੂਚਨਾਵਾਂ'
  },
  bn: {
    commandCenter: 'নির্বাচনী কমান্ড সেন্টার',
    commandCenterSub: 'গ্রাম পঞ্চায়েত রামপুর নির্বাচনের লাইভ ওভারভিউ।',
    campaignTeam: 'প্রচার দল ও অনুমতি',
    teamDescription: 'টিম সদস্য ও বুথ ইনচার্জ যোগ করুন।',
    candidateCenter: 'প্রার্থী ব্যবস্থাপনা কেন্দ্র',
    candidateDescription: 'প্রার্থী প্রোফাইল এবং প্রতীক।',
    voterDatabase: 'ভোটার তালিকা ডেটাবেস',
    voterDatabaseDesc: 'ভোটার তালিকা ব্যবস্থাপনা ও OCR স্ক্যানার।',
    studioTitle: 'ডিজাইন স্টুডিও',
    studioSub: 'পোস্টার ও ব্যানার জেনারেটর।',
    broadcastTitle: 'ব্রডকাস্ট সেন্টার',
    broadcastSub: 'হোয়াটসঅ্যাপ ও এসএমএস বার্তা পাঠান।',
    boothOps: 'বুথ কার্যক্রম',
    surveysComplaints: 'অভিযোগ ও সমীক্ষা',
    expensesLedger: 'খরচ লেজার',
    turnoutAnalytics: 'টার্নআউট অ্যানালিটিক্স',
    settingsBranding: 'সেটিংস ও ব্র্যান্ডিং',
    totalVoters: 'মোট ভোটার',
    whatsappReached: 'হোয়াটসঅ্যাপ পৌঁছেছে',
    activeTeam: 'সক্রিয় দল',
    budgetUtilized: 'ব্যয়িত বাজেট',
    searchVoters: 'ভোটার খুঁজুন...',
    allSegments: 'সব ভোটার',
    exportCsv: 'CSV এক্সপোর্ট',
    uploadRoll: 'আপলোড',
    scanOcr: 'OCR স্ক্যান',
    addCandidate: '+ প্রার্থী যোগ করুন',
    addMember: '+ সদস্য যোগ করুন',
    logGrievance: '+ অভিযোগ লিখুন',
    addExpense: '+ খরচ যোগ করুন',
    dispatchBroadcast: 'বার্তা পাঠান',
    dontHaveAccount: 'অ্যাকাউন্ট নেই? সাইন আপ করুন',
    alreadyAccount: 'অ্যাকাউন্ট আছে? লগইন করুন',
    continueDemo: 'ডেমো মোডে চালিয়ে যান',
    roleSwitcher: 'রোল পরিবর্তন',
    dashboardOverview: 'ড্যাশবোর্ড ওভারভিউ',
    currentElection: 'চলতি নির্বাচন',
    totalCandidatesOrganizations: 'মোট প্রার্থী / সংস্থা',
    candidatesAndOrganizations: 'প্রার্থী ও সংস্থা',
    totalVotersAdded: 'যোগ হওয়া ভোটার',
    liveVoterDatabase: 'লাইভ ভোটার ডেটাবেস',
    activeElections: 'সক্রিয় নির্বাচন',
    electionPortfolio: 'নির্বাচনী পোর্টফোলিও',
    recentActivity: 'সাম্প্রতিক কার্যকলাপ',
    latestUpdates: 'সর্বশেষ আপডেট',
    last5Updates: 'শেষ 5 আপডেট',
    type: 'ধরন',
    details: 'বিস্তারিত',
    time: 'সময়',
    totalVotersInElection: 'নির্বাচনে মোট ভোটার',
    volunteersCount: 'স্বেচ্ছাসেবক',
    activeVolunteers: 'সক্রিয় স্বেচ্ছাসেবক',
    messagesSentThisWeek: 'এই সপ্তাহে পাঠানো বার্তা',
    campaignReach: 'প্রচার পৌঁছান',
    wardCoverage: 'ওয়ার্ডভিত্তিক কভারেজ',
    coverageSummary: 'কভারেজ সারাংশ',
    quickActions: 'দ্রুত কাজ',
    dailyChecklist: 'দৈনিক চেকলিস্ট',
    addVoter: 'ভোটার যোগ করুন',
    createPoster: 'পোস্টার তৈরি করুন',
    sendBroadcast: 'ব্রডকাস্ট পাঠান',
    viewComplaints: 'অভিযোগ দেখুন',
    wardVotersCount: 'ওয়ার্ড ভোটার',
    wardCoverageSummary: 'আপনার ওয়ার্ড কভারেজ',
    pendingTasks: 'বাকি কাজ',
    todayChecklist: 'আজকের তালিকা',
    taskSummary: 'কাজের সারাংশ',
    assignedVoters: 'নির্ধারিত ভোটার',
    assignedVoterSummary: 'ফলো-আপ তালিকা',
    dashboardLoadError: 'ব্যাকএন্ড থেকে ডেটা লোড করা যায়নি',
    candidates: 'প্রার্থী',
    organizations: 'সংস্থা',
    volunteers: 'স্বেচ্ছাসেবক',
    recent: 'সাম্প্রতিক',
    // Auth Form
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    signIn: 'সাইন ইন',
    registerVerifiedAccount: 'যাচাইকৃত প্রচারাভিযান অ্যাকাউন্ট নিবন্ধন করুন',
    enterCredentials: 'ড্যাশবোর্ড অ্যাক্সেস করতে আপনার শংসাপত্র প্রবেশ করুন',
    firstName: 'প্রথম নাম',
    enterFirstName: 'প্রথম নাম প্রবেশ করুন',
    lastName: 'শেষ নাম',
    enterLastName: 'শেষ নাম প্রবেশ করুন',
    emailAddress: 'ইমেল ঠিকানা',
    password: 'পাসওয়ার্ড',
    createPassword: 'পাসওয়ার্ড তৈরি করুন',
    enterPassword: 'আপনার পাসওয়ার্ড প্রবেশ করুন',
    authenticating: 'প্রমাণীকরণ করা হচ্ছে...',
    creatingAccount: 'অ্যাকাউন্ট তৈরি করা হচ্ছে...',
    or: 'অথবা',
    alreadyHaveAccountLogin: 'ইতিমধ্যে অ্যাকাউন্ট আছে? সাইন ইন করুন',
    quickDemoLogin: '🎯 দ্রুত ডেমো লগইন (সুপার অ্যাডমিন)',
    signUpNewAccount: 'নতুন অ্যাকাউন্টের জন্য সাইন আপ করুন',
    multiTenantNote: 'মাল্টি-টেন্যান্ট · JWT প্রমাণীকরণ · অনুমতি-ভিত্তিক RBAC',
    realTimeElection: 'রিয়েল-টাইম নির্বাচন প্রচার ব্যবস্থাপনা',
    voterDataVolunteer: 'ভোটার ডেটা · স্বেচ্ছাসেবক ব্যবস্থাপনা · ডিজাইন স্টুডিও · স্মার্ট সম্প্রচার · বিশ্লেষণ ড্যাশবোর্ড',
    roleBasedAccess: 'ভূমিকা-ভিত্তিক অ্যাক্সেস নিয়ন্ত্রণ (RBAC)',
    multiTenantOrg: 'মাল্টি-টেন্যান্ট সংস্থা বিচ্ছিন্নতা',
    realtimeDashboard: 'রিয়েল-টাইম ড্যাশবোর্ড এবং বিশ্লেষণ',
    masterCampaignOS: '🇮🇳 মাস্টার প্রচারাভিযান OS এবং ওয়ার রুম',
    // Form validation
    fieldRequired: 'এই ক্ষেত্র প্রয়োজনীয়',
    invalidEmail: 'দয়া করে একটি বৈধ ইমেল প্রবেশ করুন',
    passwordMismatch: 'পাসওয়ার্ড মেলে না',
    // Success/Error messages
    welcomeMessage: 'ElectWin ওয়ার রুমে স্বাগতম!',
    enteredAsAdmin: 'সুপার অ্যাডমিন হিসাবে ElectWin এ প্রবেশ করেছেন (ডেমো মোড)',
    accountCreated: 'অ্যাকাউন্ট তৈরি করা হয়েছে। আপনার শংসাপত্র দিয়ে সাইন ইন করুন।',
    invalidCredentials: 'অবৈধ ইমেল বা পাসওয়ার্ড।',
    backendNotRunning: 'ডেমো লগইন ব্যর্থ — নিশ্চিত করুন যে ব্যাকএন্ড পোর্ট 8000 এ চলছে।',
    signUpFailed: 'সাইন আপ ব্যর্থ।',
    // Common actions
    save: 'সংরক্ষণ করুন',
    cancel: 'বাতিল করুন',
    delete: 'মুছে দিন',
    edit: 'সম্পাদনা করুন',
    close: 'বন্ধ করুন',
    submit: 'জমা দিন',
    back: 'পিছনে',
    next: 'পরবর্তী',
    // Table actions
    action: 'পদক্ষেপ',
    status: 'অবস্থা',
    name: 'নাম',
    email: 'ইমেল',
    phone: 'ফোন',
    date: 'তারিখ',
    // Dashboard specific
    totalVotersReachable: 'মোট ভোটার (পৌঁছানো যায়)',
    broadcastsDispatched: 'সম্প্রচার পাঠানো হয়েছে',
    successRate: 'সাফল্যের হার',
    teamMembersCount: 'দল সদস্যদের সংখ্যা',
    // Navigation items
    navigationSidebarCampaignMgmt: 'প্রচার ব্যবস্থাপনা',
    navigationSidebarFieldVolunteer: 'ক্ষেত্র স্বেচ্ছাসেবক ডেস্ক',
    navItemWarRoomDashboard: 'যুদ্ধ কক্ষ ড্যাশবোর্ড',
    navItemTeamPermissions: 'দল এবং অনুমতি',
    navItemCandidatesSymbols: 'প্রার্থী এবং প্রতীক',
    navItemVoterRollOCR: 'ভোটার তালিকা এবং OCR',
    navItemDesignStudio: 'ডিজাইন স্টুডিও',
    navItemBroadcastCenter: 'সম্প্রচার কেন্দ্র',
    navItemBoothOperations: 'বুথ পরিচালনা',
    navItemSurveysGrievances: 'অভিযোগ এবং সমীক্ষা',
    navItemECExpensesLedger: 'খরচ লেজার',
    navItemTurnoutAnalytics: 'ভোট বিশ্লেষণ',
    navItemSettingsBranding: 'সেটিংস এবং ব্র্যান্ডিং',
    navItemWardFieldDesk: 'ওয়ার্ড 02 ক্ষেত্র ডেস্ক',
    navItemAddElector: 'ভোটার যোগ করুন (ওয়ার্ড 02)',
    navItemFieldRecord: 'আমার ক্ষেত্র রেকর্ড',
    navItemSignOut: 'সেশন থেকে বেরিয়ে যান',
    mobileNavWarRoom: 'যুদ্ধ কক্ষ',
    mobileNavVoters: 'ভোটার',
    mobileNavStudio: 'স্টুডিও',
    mobileNavBroadcast: 'সম্প্রচার',
    mobileNavFieldDesk: 'ক্ষেত্র ডেস্ক',
    navbarToggleSidebar: 'নেভিগেশন ড্রয়ার টগল করুন',
    navbarChangeLanguage: 'ভাষা পরিবর্তন করুন',
    navbarLiveNotifications: 'লাইভ বিজ্ঞপ্তি'
  },
  mr: {
    commandCenter: 'निवडणूक मोहीम वॉर रूम',
    commandCenterSub: 'ग्रामपंचायत रामपूर निवडणुकीचा थेट आढावा.',
    campaignTeam: 'मोहीम टीम आणि परवानग्या',
    teamDescription: 'मोहीम व्यवस्थापक आणि बूथ प्रमुख जोडा.',
    candidateCenter: 'उमेदवार व्यवस्थापन केंद्र',
    candidateDescription: 'उमेदवार प्रोफाइल, चिन्ह आणि जाहीरनामा.',
    voterDatabase: 'मतदार यादी व डेटाबेस',
    voterDatabaseDesc: 'मतदार यादी व्यवस्थापन आणि कॅमेरा OCR स्कॅनर.',
    studioTitle: 'डिझाइन स्टुडिओ',
    studioSub: 'पोस्टर, बॅनर आणि व्हॉट्सअॅप स्टेटस कार्ड तयार करा.',
    broadcastTitle: 'प्रसारण व संदेश केंद्र',
    broadcastSub: 'व्हॉट्सअॅप आणि एसएमएस द्वारे थेट मतदारांपर्यंत पोहोचा.',
    boothOps: 'बूथ कामकाज',
    surveysComplaints: 'तक्रारी व सर्वेक्षण',
    expensesLedger: 'खर्च नोंदवही',
    turnoutAnalytics: 'मतदान विश्लेषण',
    settingsBranding: 'सेटिंग्ज व ब्रँडिंग',
    totalVoters: 'एकूण मतदार',
    whatsappReached: 'व्हॉट्सअॅप संपर्क',
    activeTeam: 'सक्रिय टीम',
    budgetUtilized: 'खर्च केलेला निधी',
    searchVoters: 'मतदार शोधा...',
    allSegments: 'सर्व मतदार',
    exportCsv: 'CSV डाउनलोड',
    uploadRoll: 'यादी अपलोड करा',
    scanOcr: 'OCR स्कॅन',
    addCandidate: '+ उमेदवार जोडा',
    addMember: '+ सदस्य जोडा',
    logGrievance: '+ तक्रार नोंदवा',
    addExpense: '+ खर्च जोडा',
    dispatchBroadcast: 'संदेश पाठवा',
    dontHaveAccount: 'खाते नाही? साइन अप करा',
    alreadyAccount: 'आधीच खाते आहे? लॉगिन करा',
    continueDemo: 'लॉगिन न करता डेमो पाहा',
    roleSwitcher: 'भूमिका बदला',
    dashboardOverview: 'डॅशबोर्ड ओव्हरव्ह्यू',
    currentElection: 'सध्याचा निवडणूक',
    totalCandidatesOrganizations: 'एकूण उमेदवार / संस्था',
    candidatesAndOrganizations: 'उमेदवार आणि संस्था',
    totalVotersAdded: 'जोडलेले एकूण मतदार',
    liveVoterDatabase: 'लाइव्ह मतदार डेटाबेस',
    activeElections: 'सक्रिय निवडणुका',
    electionPortfolio: 'निवडणूक पोर्टफोलिओ',
    recentActivity: 'अलीकडील क्रियाकलाप',
    latestUpdates: 'ताज्या अपडेट्स',
    last5Updates: 'अखेरचे 5 अपडेट्स',
    type: 'प्रकार',
    details: 'तपशील',
    time: 'वेळ',
    totalVotersInElection: 'निवडणूकीतील एकूण मतदार',
    volunteersCount: 'स्वयंसेवक',
    activeVolunteers: 'सक्रिय स्वयंसेवक',
    messagesSentThisWeek: 'या आठवड्यात पाठवलेले संदेश',
    campaignReach: 'प्रचार पोहोच',
    wardCoverage: 'वार्डनिहाय कव्हरेज',
    coverageSummary: 'कव्हरेज सारांश',
    quickActions: 'जलद कृती',
    dailyChecklist: 'दैनिक चेकलिस्ट',
    addVoter: 'मतदार जोडा',
    createPoster: 'पोस्टर बनवा',
    sendBroadcast: 'ब्रॉडकास्ट पाठवा',
    viewComplaints: 'तक्रारी पहा',
    wardVotersCount: 'वार्ड मतदार',
    wardCoverageSummary: 'तुमचा वार्ड कव्हरेज',
    pendingTasks: 'प्रलंबित कामे',
    todayChecklist: 'आजची यादी',
    taskSummary: 'काम सारांश',
    assignedVoters: 'नियुक्त मतदार',
    assignedVoterSummary: 'फॉलो-अप यादी',
    dashboardLoadError: 'बॅकएंडमधून डेटा लोड झाला नाही',
    candidates: 'उमेदवार',
    organizations: 'संस्था',
    volunteers: 'स्वयंसेवक',
    recent: 'अलीकडील',
    // Auth Form
    createAccount: 'खाते तयार करा',
    signIn: 'साइन इन करा',
    registerVerifiedAccount: 'सत्यापित प्रचार खाते नोंदणी करा',
    enterCredentials: 'डॅशबोर्डमध्ये प्रवेशासाठी आपली क्रेडेंशियल्स प्रविष्ट करा',
    firstName: 'पहिले नाव',
    enterFirstName: 'पहिले नाव प्रविष्ट करा',
    lastName: 'शेवटचे नाव',
    enterLastName: 'शेवटचे नाव प्रविष्ट करा',
    emailAddress: 'ईमेल पत्ता',
    password: 'पासवर्ड',
    createPassword: 'पासवर्ड तयार करा',
    enterPassword: 'आपला पासवर्ड प्रविष्ट करा',
    authenticating: 'प्रमाणिकरण करत आहे...',
    creatingAccount: 'खाते तयार करत आहे...',
    or: 'किंवा',
    alreadyHaveAccountLogin: 'आधीच खाते आहे? साइन इन करा',
    quickDemoLogin: '🎯 द्रुत डेमो लॉगइन (सुपर अॅडमिन)',
    signUpNewAccount: 'नव्या खात्यासाठी साइन अप करा',
    multiTenantNote: 'मल्टी-टेनंट · JWT प्रमाणीकरण · परवानगी-आधारित RBAC',
    realTimeElection: 'रिअल-टाइम निवडणूक प्रचार व्यवस्थापन',
    voterDataVolunteer: 'मतदार डेटा · स्वयंसेवक व्यवस्थापन · डिजाइन स्टुडिओ · स्मार्ट प्रसारण · विश्लेषण डॅशबोर्ड',
    roleBasedAccess: 'भूमिका-आधारित प्रवेश नियंत्रण (RBAC)',
    multiTenantOrg: 'मल्टी-टेनंट संस्था अलगीकरण',
    realtimeDashboard: 'रिअल-टाइम डॅशबोर्ड आणि विश्लेषण',
    masterCampaignOS: '🇮🇳 मास्टर प्रचार OS आणि वॉर रूम',
    // Form validation
    fieldRequired: 'हे क्षेत्र आवश्यक आहे',
    invalidEmail: 'कृपया वैध ईमेल प्रविष्ट करा',
    passwordMismatch: 'पासवर्ड जुळत नाहीत',
    // Success/Error messages
    welcomeMessage: 'ElectWin वॉर रूममध्ये स्वागतम!',
    enteredAsAdmin: 'ElectWin मध्ये सुपर अॅडमिन म्हणून प्रवेश केला (डेमो मोड)',
    accountCreated: 'खाते तयार केले गेले. कृपया आपली क्रेडेंशियल्स सह साइन इन करा.',
    invalidCredentials: 'अमान्य ईमेल किंवा पासवर्ड.',
    backendNotRunning: 'डेमो लॉगइन अयशस्वी — सुनिश्चित करा की बॅकएंड पोर्ट 8000 वर चल रहा आहे.',
    signUpFailed: 'साइन अप अयशस्वी.',
    // Common actions
    save: 'जतन करा',
    cancel: 'रद्द करा',
    delete: 'हटवा',
    edit: 'संपादित करा',
    close: 'बंद करा',
    submit: 'सबमिट करा',
    back: 'मागे',
    next: 'पुढे',
    // Table actions
    action: 'कृती',
    status: 'स्थिती',
    name: 'नाव',
    email: 'ईमेल',
    phone: 'फोन',
    date: 'तारीख',
    // Dashboard specific
    totalVotersReachable: 'एकूण मतदार (पोहोचण्यायोग्य)',
    broadcastsDispatched: 'प्रसारण पाठवले गेले',
    successRate: 'यश दर',
    teamMembersCount: 'संघ सदस्यांची संख्या',
    // Navigation items
    navigationSidebarCampaignMgmt: 'प्रचार व्यवस्थापन',
    navigationSidebarFieldVolunteer: 'क्षेत्र स्वयंसेवक डेस्क',
    navItemWarRoomDashboard: 'वॉर रूम डॅशबोर्ड',
    navItemTeamPermissions: 'टीम आणि परवानग्या',
    navItemCandidatesSymbols: 'उमेदवार आणि चिन्ह',
    navItemVoterRollOCR: 'मतदार यादी आणि OCR',
    navItemDesignStudio: 'डिझाइन स्टुडिओ',
    navItemBroadcastCenter: 'प्रसारण केंद्र',
    navItemBoothOperations: 'बूथ कामकाज',
    navItemSurveysGrievances: 'तक्रारी आणि सर्वेक्षण',
    navItemECExpensesLedger: 'खर्च नोंदवही',
    navItemTurnoutAnalytics: 'मतदान विश्लेषण',
    navItemSettingsBranding: 'सेटिंग्ज आणि ब्रँडिंग',
    navItemWardFieldDesk: 'वार्ड 02 क्षेत्र डेस्क',
    navItemAddElector: 'मतदार जोडा (वार्ड 02)',
    navItemFieldRecord: 'माझा क्षेत्र रेकॉर्ड',
    navItemSignOut: 'सेशन बाहेर निघा',
    mobileNavWarRoom: 'वॉर रूम',
    mobileNavVoters: 'मतदार',
    mobileNavStudio: 'स्टुडिओ',
    mobileNavBroadcast: 'प्रसारण',
    mobileNavFieldDesk: 'क्षेत्र डेस्क',
    navbarToggleSidebar: 'नेव्हिगेशन ड्रॉअर टॉगल करा',
    navbarChangeLanguage: 'भाषा बदला',
    navbarLiveNotifications: 'लाइव्ह सूचना'
  },
  te: {
    commandCenter: 'ఎన్నికల ప్రచార కమాండ్ సెంటర్',
    commandCenterSub: 'గ్రామ పంచాయతీ రాంపూర్ ఎన్నికల ప్రత్యక్ష సమాచారం.',
    campaignTeam: 'ప్రచార బృందం & అనుమతులు',
    teamDescription: 'మేనేజర్లు మరియు బూత్ ఇన్‌ఛార్జ్‌లను జోడించండి.',
    candidateCenter: 'అభ్యర్థుల నిర్వహణ కేంద్రం',
    candidateDescription: 'అభ్యర్థుల ప్రొఫైల్స్, చిహ్నాలు మరియు మేనిఫెస్టో.',
    voterDatabase: 'ఓటరు జాబితా & డేటాబేస్',
    voterDatabaseDesc: 'ఓటరు జాబితా నిర్వహణ & OCR స్కానర్.',
    studioTitle: 'డిజైన్ స్టూడియో',
    studioSub: 'పోస్టర్లు, ఫ్లెక్స్ బ్యానర్లు తయారు చేయండి.',
    broadcastTitle: 'సందేశ కేంద్రం',
    broadcastSub: 'వాట్సాప్ & SMS ద్వారా ఓటర్లకు సందేశాలు పంపండి.',
    boothOps: 'బూత్ కార్యకలాపాలు',
    surveysComplaints: 'ఫిర్యాదులు & సర్వేలు',
    expensesLedger: 'ఖర్చుల లెడ్జర్',
    turnoutAnalytics: 'ఓటింగ్ విశ్లేషణ',
    settingsBranding: 'సెట్టింగ్‌లు',
    totalVoters: 'మొత్తం ఓటర్లు',
    whatsappReached: 'వాట్సాప్ రీచ్',
    activeTeam: 'క్రియాశీల బృందం',
    budgetUtilized: 'ఖర్చు చేసిన బడ్జెట్',
    searchVoters: 'ఓటరును వెతకండి...',
    allSegments: 'అందరు ఓటర్లు',
    exportCsv: 'CSV డౌన్‌లోడ్',
    uploadRoll: 'అప్‌లోడ్ చేయండి',
    scanOcr: 'OCR స్కాన్',
    addCandidate: '+ అభ్యర్థిని జోడించండి',
    addMember: '+ సభ్యుడిని జోడించండి',
    logGrievance: '+ ఫిర్యాదు నమోదు చేయండి',
    addExpense: '+ ఖర్చును జోడించండి',
    dispatchBroadcast: 'సందేశం పంపండి',
    dontHaveAccount: 'ఖాతా లేదా? సైన్ అప్ చేయండి',
    alreadyAccount: 'ఖాతా ఉందా? లాగిన్ అవ్వండి',
    continueDemo: 'డెమో కొనసాగించండి',
    roleSwitcher: 'పాత్రను మార్చండి',
    dashboardOverview: 'డాష్‌బోర్డ్ అవలోకనం',
    currentElection: 'ప్రస్తుత ఎన్నిక',
    totalCandidatesOrganizations: 'మొత్తం అభ్యర్థులు / సంస్థలు',
    candidatesAndOrganizations: 'అభ్యర్థులు మరియు సంస్థలు',
    totalVotersAdded: 'చేర్చబడిన మొత్తం ఓటర్లు',
    liveVoterDatabase: 'లైవ్ ఓటర్ డేటాబేస్',
    activeElections: 'క్రియాశీల ఎన్నికలు',
    electionPortfolio: 'ఎన్నిక పోర్ట్‌ఫోలియో',
    recentActivity: 'సమీప కార్యకలాపాలు',
    latestUpdates: 'చివరి నవీకరణలు',
    last5Updates: 'చివరి 5 నవీకరణలు',
    type: 'రకం',
    details: 'వివరాలు',
    time: 'సమయం',
    totalVotersInElection: 'ఎన్నికలో మొత్తం ఓటర్లు',
    volunteersCount: 'స్వచ్ఛంద సేవకులు',
    activeVolunteers: 'క్రియాశీల స్వచ్ఛంద సేవకులు',
    messagesSentThisWeek: 'ఈ వారం పంపిన సందేశాలు',
    campaignReach: 'ప్రచారం చేరింపు',
    wardCoverage: 'వార్డు వారీ కవరేజ్',
    coverageSummary: 'కవరేజ్ సమీక్ష',
    quickActions: 'త్వరిత చర్యలు',
    dailyChecklist: 'రోజువారీ చెక్‌లిస్ట్',
    addVoter: 'ఓటరును జోడించండి',
    createPoster: 'పోస్టర్ సృష్టించండి',
    sendBroadcast: 'బ్రాడ్‌కాస్ట్ పంపండి',
    viewComplaints: 'ఫిర్యాదులు చూడండి',
    wardVotersCount: 'వార్డు ఓటర్లు',
    wardCoverageSummary: 'మీ వార్డు కవరేజ్',
    pendingTasks: 'బాకీ పనులు',
    todayChecklist: 'ఈరోజు పనుల జాబితా',
    taskSummary: 'పని సంగ్రహం',
    assignedVoters: 'నియమించిన ఓటర్లు',
    assignedVoterSummary: 'ఫాలో-అప్ జాబితా',
    dashboardLoadError: 'బ్యాకెండ్ నుంచి డేటా లోడ్ కాలేదు',
    candidates: 'అభ్యర్థులు',
    organizations: 'సంస్థలు',
    volunteers: 'స్వచ్ఛంద సేవకులు',
    recent: 'ఇటీవలి',
    // Auth Form
    createAccount: 'ఖాతా సృష్టించండి',
    signIn: 'సైన్ ఇన్',
    registerVerifiedAccount: 'ధృవీకృత ప్రచార ఖాతాను నమోదు చేయండి',
    enterCredentials: 'డ్యాష్‌బోర్డ్ యాక్సెస్ చేయడానికి మీ నిఖర్చలను నమోదు చేయండి',
    firstName: 'మొదటి పేరు',
    enterFirstName: 'మొదటి పేరు నమోదు చేయండి',
    lastName: 'చివరి పేరు',
    enterLastName: 'చివరి పేరు నమోదు చేయండి',
    emailAddress: 'ఇమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    createPassword: 'పాస్‌వర్డ్ సృష్టించండి',
    enterPassword: 'మీ పాస్‌వర్డ్ నమోదు చేయండి',
    authenticating: 'ధృవీకరిస్తోంది...',
    creatingAccount: 'ఖాతా సృష్టిస్తోంది...',
    or: 'లేదా',
    alreadyHaveAccountLogin: 'ఇప్పటికే ఖాతా ఉందా? సైన్ ఇన్ చేయండి',
    quickDemoLogin: '🎯 త్వరిత డెమో లాగిన్ (సూపర్ అడ్మిన్)',
    signUpNewAccount: 'కొత్త ఖాతాకు సైన్ అప్ చేయండి',
    multiTenantNote: 'మల్టీ-టెనెంట్ · JWT ప్రామాణీకరణ · అనుమతి-ఆధారిత RBAC',
    realTimeElection: 'రియల్-టైమ్ ఎన్నికల ప్రచార నిర్వహణ',
    voterDataVolunteer: 'ఓటరు డేటా · స్వచ్ఛంద సేవక నిర్వహణ · డిజైన్ స్టూడియో · స్మార్ట్ ప్రసారణ · విశ్లేషణ డ్యాష్‌బోర్డ్',
    roleBasedAccess: 'పాత్ర-ఆధారిత ప్రవేశ నియంత్రణ (RBAC)',
    multiTenantOrg: 'మల్టీ-టెనెంట్ సంస్థ వేరుచేయడం',
    realtimeDashboard: 'రియల్-టైమ్ డ్యాష్‌బోర్డ్ మరియు విశ్లేషణ',
    masterCampaignOS: '🇮🇳 మాస్టర్ ప్రచార OS మరియు యుద్ధ గది',
    // Form validation
    fieldRequired: 'ఈ ఫీల్డ్ అవసరం',
    invalidEmail: 'దయచేసి చెల్లుబాటు అయ్యే ఇమెయిల్ నమోదు చేయండి',
    passwordMismatch: 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు',
    // Success/Error messages
    welcomeMessage: 'ElectWin యుద్ధ గదికి స్వాగతం!',
    enteredAsAdmin: 'సూపర్ అడ్మిన్‌గా ElectWin కు ప్రవేశించారు (డెమో మోడ్)',
    accountCreated: 'ఖాతా సృష్టించబడింది. దయచేసి మీ నిఖర్చలతో సైన్ ఇన్ చేయండి.',
    invalidCredentials: 'చెల్లని ఇమెయిల్ లేదా పాస్‌వర్డ్.',
    backendNotRunning: 'డెమో లాగిన్ విఫలమైంది — బ్యాకెండ్ పోర్ట్ 8000 పై నడుస్తున్నట్లు నిర్ధారించుకోండి.',
    signUpFailed: 'సైన్ అప్ విఫలమైంది.',
    // Common actions
    save: 'సేవ్ చేయండి',
    cancel: 'రద్దు చేయండి',
    delete: 'తొలగించండి',
    edit: 'సవరించండి',
    close: 'మూయండి',
    submit: 'సమర్పించండి',
    back: 'తిరిగి',
    next: 'తర్వాత',
    // Table actions
    action: 'చర్య',
    status: 'స్థితి',
    name: 'పేరు',
    email: 'ఇమెయిల్',
    phone: 'ఫోన్',
    date: 'తేదీ',
    // Dashboard specific
    totalVotersReachable: 'మొత్తం ఓటర్లు (చేరుకోలేనిది)',
    broadcastsDispatched: 'ప్రసారణలు పంపబడ్డాయి',
    successRate: 'సఫల్యత రేటు',
    teamMembersCount: 'టీమ్ సభ్యుల సంఖ్య',
    // Navigation items
    navigationSidebarCampaignMgmt: 'ప్రచార నిర్వహణ',
    navigationSidebarFieldVolunteer: 'ఫీల్డ్ స్వచ్ఛంద సేవక డెస్క్',
    navItemWarRoomDashboard: 'యుద్ధ గది డాష్‌బోర్డ్',
    navItemTeamPermissions: 'టీమ్ మరియు అనుమతులు',
    navItemCandidatesSymbols: 'అభ్యర్థులు మరియు చిహ్నాలు',
    navItemVoterRollOCR: 'ఓటరు రోల్ మరియు OCR',
    navItemDesignStudio: 'డిజైన్ స్టూడియో',
    navItemBroadcastCenter: 'ప్రసారణ కేంద్రం',
    navItemBoothOperations: 'బూత్ కార్యకలాపాలు',
    navItemSurveysGrievances: 'సర్వేలు మరియు ఫిర్యాదులు',
    navItemECExpensesLedger: 'ఖర్చుల లెడ్జర్',
    navItemTurnoutAnalytics: 'ఆటింగ్ విశ్లేషణ',
    navItemSettingsBranding: 'సెట్టింగ్‌లు మరియు బ్రాండింగ్',
    navItemWardFieldDesk: 'వార్డ్ 02 ఫీల్డ్ డెస్క్',
    navItemAddElector: 'ఓటరుని జోడించండి (వార్డ్ 02)',
    navItemFieldRecord: 'నా ఫీల్డ్ రికార్డ్',
    navItemSignOut: 'సెషన్ నుండి సైన్ అవుట్ చేయండి',
    mobileNavWarRoom: 'యుద్ధ గది',
    mobileNavVoters: 'ఓటర్లు',
    mobileNavStudio: 'స్టూడియో',
    mobileNavBroadcast: 'ప్రసారణ',
    mobileNavFieldDesk: 'ఫీల్డ్ డెస్క్',
    navbarToggleSidebar: 'నావిగేషన్ డ్రాయర్ టాగిల్',
    navbarChangeLanguage: 'భాషను మార్చండి',
    navbarLiveNotifications: 'లైవ్ నోటిఫికేషన్లు'
  },
  ta: {
    commandCenter: 'தேர்தல் பிரச்சார கட்டளை மையம்',
    commandCenterSub: 'கிராம பஞ்சாயத்து ராம்பூர் தேர்தல் நேரலை கண்ணோட்டம்.',
    campaignTeam: 'பிரச்சாரக் குழு மற்றும் அனுமதிகள்',
    teamDescription: 'நிர்வாகிகள் மற்றும் பூத் பொறுப்பாளர்களை சேர்க்கவும்.',
    candidateCenter: 'வேட்பாளர் மேலாண்மை மையம்',
    candidateDescription: 'வேட்பாளர் விவரங்கள், சின்னங்கள் மற்றும் தேர்தல் அறிக்கை.',
    voterDatabase: 'வாக்காளர் பட்டியல் தரவுத்தளம்',
    voterDatabaseDesc: 'வாக்காளர் பட்டியல் மேலாண்மை & OCR ஸ்கேனர்.',
    studioTitle: 'வடிவமைப்பு ஸ்டுடியோ',
    studioSub: 'சுவரொட்டிகள், பேனர்கள் மற்றும் வாட்ஸ்அப் கார்டுகள் உருவாக்கவும்.',
    broadcastTitle: 'செய்தி ஒளிபரப்பு மையம்',
    broadcastSub: 'வாட்ஸ்அப் மற்றும் SMS வழியே செய்தி அனுப்பவும்.',
    boothOps: 'பூத் செயல்பாடுகள்',
    surveysComplaints: 'புகார்கள் & ஆய்வுகள்',
    expensesLedger: 'செலவு கணக்கு',
    turnoutAnalytics: 'வாக்குப்பதிவு பகுப்பாய்வு',
    settingsBranding: 'அமைப்புகள் & பிராண்டிங்',
    totalVoters: 'மொத்த வாக்காளர்கள்',
    whatsappReached: 'வாட்ஸ்அப் சென்றடைந்தது',
    activeTeam: 'செயலில் உள்ள குழு',
    budgetUtilized: 'செலவிடப்பட்ட நிதி',
    searchVoters: 'வாக்காளரைத் தேடுங்கள்...',
    allSegments: 'அனைத்து வாக்காளர்கள்',
    exportCsv: 'CSV பதிவிறக்கம்',
    uploadRoll: 'பதிவேற்றம்',
    scanOcr: 'OCR ஸ்கேன்',
    addCandidate: '+ வேட்பாளரைச் சேர்',
    addMember: '+ உறுப்பினரைச் சேர்',
    logGrievance: '+ புகார் பதிவு செய்',
    addExpense: '+ செலவு சேர்',
    dispatchBroadcast: 'செய்தி அனுப்புக',
    dontHaveAccount: 'கணக்கு இல்லையா? பதிவு செய்க',
    alreadyAccount: 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக',
    continueDemo: 'டெமோ தொடரவும்',
    roleSwitcher: 'பங்கை மாற்றவும்',
    dashboardOverview: 'டாஷ்போர்டு கண்ணோட்டம்',
    currentElection: 'தற்போதைய தேர்தல்',
    totalCandidatesOrganizations: 'மொத்த வேட்பாளர்கள் / அமைப்புகள்',
    candidatesAndOrganizations: 'வேட்பாளர்கள் மற்றும் அமைப்புகள்',
    totalVotersAdded: 'சேர்க்கப்பட்ட மொத்த வாக்காளர்கள்',
    liveVoterDatabase: 'லைவ் வாக்காளர் தரவுத்தளம்',
    activeElections: 'செயலில் உள்ள தேர்தல்கள்',
    electionPortfolio: 'தேர்தல் போர்ட்ஃபோலியோ',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    latestUpdates: 'சமீபத்திய புதுப்பிப்புகள்',
    last5Updates: 'சமீப 5 புதுப்பிப்புகள்',
    type: 'வகை',
    details: 'விவரங்கள்',
    time: 'நேரம்',
    totalVotersInElection: 'தேர்தலில் மொத்த வாக்காளர்கள்',
    volunteersCount: 'தன்னார்வலர்கள்',
    activeVolunteers: 'செயலில் உள்ள தன்னார்வலர்கள்',
    messagesSentThisWeek: 'இந்த வாரம் அனுப்பப்பட்ட செய்திகள்',
    campaignReach: 'பிரச்சாரத்தை எட்டியது',
    wardCoverage: 'வார்டு வாரியாக உள்ளடக்கம்',
    coverageSummary: 'கவரேஜ் சுருக்கம்',
    quickActions: 'விரைவு செயல்கள்',
    dailyChecklist: 'செய்தி பட்டியல்',
    addVoter: 'வாக்காளரைச் சேர்க்கவும்',
    createPoster: 'போஸ்டர் உருவாக்கவும்',
    sendBroadcast: 'பிரசாரத்தை அனுப்பவும்',
    viewComplaints: 'புகார்களைப் பார்க்கவும்',
    wardVotersCount: 'வார்டு வாக்காளர்கள்',
    wardCoverageSummary: 'உங்கள் வார்டு கவரேஜ்',
    pendingTasks: 'நிலுவையில் உள்ள பணிகள்',
    todayChecklist: 'இன்றைய பட்டியல்',
    taskSummary: 'பணி சுருக்கம்',
    assignedVoters: 'ஒதுக்கப்பட்ட வாக்காளர்கள்',
    assignedVoterSummary: 'பின்தொடர்தல் பட்டியல்',
    dashboardLoadError: 'பின்தளத்திலிருந்து தரவு ஏற்றப்படவில்லை',
    candidates: 'வேட்பாளர்கள்',
    organizations: 'நிறுவனங்கள்',
    volunteers: 'தன்னார்வலர்கள்',
    recent: 'சமீபத்திய',
    // Auth Form
    createAccount: 'கணக்கை உருவாக்கவும்',
    signIn: 'உள்நுழைக',
    registerVerifiedAccount: 'சரிபார்க்கப்பட்ட பிரচாரக் கணக்கை பதிவு செய்யவும்',
    enterCredentials: 'பணிச்சாளக கணக்கை அணுக உங்கள் நற்சான்றிதழ்களை உள்ளிடவும்',
    firstName: 'முதல் பெயர்',
    enterFirstName: 'முதல் பெயரை உள்ளிடவும்',
    lastName: 'கடைசி பெயர்',
    enterLastName: 'கடைசி பெயரை உள்ளிடவும்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    createPassword: 'கடவுச்சொல்லை உருவாக்கவும்',
    enterPassword: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    authenticating: 'ஆதாரப்படுத்தப்படுகிறது...',
    creatingAccount: 'கணக்கை உருவாக்குகிறது...',
    or: 'அல்லது',
    alreadyHaveAccountLogin: 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக',
    quickDemoLogin: '🎯 விரைவான ஆய்வு உள்நுழைவு (சூப்பர் நிர்வாகி)',
    signUpNewAccount: 'புதிய கணக்குக்கு பதிவு செய்யவும்',
    multiTenantNote: 'மல்டி-குத்தகை · JWT சரிபார்ப்பு · அனுமதி-அடிப்படையிலான RBAC',
    realTimeElection: 'நிகழ் நேர தேர்தல் பிரச்சாரத் திட்டமிடல்',
    voterDataVolunteer: 'வாக்காளர் தரவு · தன்னார்வலர் மேலாண்மை · வடிவமைப்பு ஸ்টுடியோ · ஸ்மார்ட் ஒளிபரப்பு · பகுப்பாய்வு பணிச்சாளக',
    roleBasedAccess: 'பங்கு-அடிப்படையிலான அணுக கட்டுப்பாடு (RBAC)',
    multiTenantOrg: 'மல்டி-குத்தகை நிறுவனத்தின் பிரிவினை',
    realtimeDashboard: 'நிகழ் நேர பணிச்சாளக மற்றும் பகுப்பாய்வு',
    masterCampaignOS: '🇮🇳 மாஸ்டர் பிரச்சாரம் OS மற்றும் யுদ்ধ அறை',
    // Form validation
    fieldRequired: 'இந்த புலம் தேவை',
    invalidEmail: 'தயவு செய்து சரியான மின்னஞ்சலை உள்ளிடவும்',
    passwordMismatch: 'கடவுச்சொற்கள் பொருந்தவில்லை',
    // Success/Error messages
    welcomeMessage: 'ElectWin போர் அரைக்கு வரவேற்கிறோம்!',
    enteredAsAdmin: 'சூப்பர் நிர்வாகி என ElectWin க்கு நுழைந்துவிட்டீர்கள் (ஆய்வு பயன்முறை)',
    accountCreated: 'கணக்கை உருவாக்கினர். தயவு செய்து உங்கள் நற்சான்றிதழ்களுடன் உள்நுழைக.',
    invalidCredentials: 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்.',
    backendNotRunning: 'ஆய்வு உள்நுழைவு தோல்வியுற்றது — பின்உறுப்பு போர்ட் 8000 இல் চলுவதை உறுதிசெய்க.',
    signUpFailed: 'பதிவு தோல்வியுற்றது.',
    // Common actions
    save: 'சேமிக்கவும்',
    cancel: 'ரத்து செய்யவும்',
    delete: 'நீக்கவும்',
    edit: 'திருத்தவும்',
    close: 'மூடு',
    submit: 'சமர்ப்பிக்கவும்',
    back: 'பின்னுக்கு',
    next: 'அடுத்தது',
    // Table actions
    action: 'செயல்',
    status: 'நிலை',
    name: 'பெயர்',
    email: 'மின்னஞ்சல்',
    phone: 'தொலைபேசி',
    date: 'தேதி',
    // Dashboard specific
    totalVotersReachable: 'மொத்த வாக்காளர் (சேர்க்க முடிந்த)',
    broadcastsDispatched: 'ஒளிபரப்பு அனுப்பப்பட்டவை',
    successRate: 'வெற்றிக் கட்டணம்',
    teamMembersCount: 'குழு உறுப்பினர்களின் எண்ணிக்கை',
    // Navigation items
    navigationSidebarCampaignMgmt: 'பிரச்சாரத் திட்டமிடல்',
    navigationSidebarFieldVolunteer: 'ஃபீல்ட் தன்னார்வலர் டெஸ்க்',
    navItemWarRoomDashboard: 'யுத்த அறை டாஷ்போர்டு',
    navItemTeamPermissions: 'குழு மற்றும் அனுமதிகள்',
    navItemCandidatesSymbols: 'வேட்பாளர்கள் மற்றும் சின்னங்கள்',
    navItemVoterRollOCR: 'வாக்காளர் பட்டியல் மற்றும் OCR',
    navItemDesignStudio: 'வடிவமைப்பு ஸ்டுடியோ',
    navItemBroadcastCenter: 'ஒளிபரப்பு மையம்',
    navItemBoothOperations: 'பூத் செயல்பாடுகள்',
    navItemSurveysGrievances: 'ஆய்வுகள் மற்றும் புகார்கள்',
    navItemECExpensesLedger: 'செலவு கணக்கு',
    navItemTurnoutAnalytics: 'ஓட்டுப் பகுப்பாய்வு',
    navItemSettingsBranding: 'அமைப்புகள் மற்றும் பிராண்டிங்',
    navItemWardFieldDesk: 'வார்டு 02 ஃபீல்ட் டெஸ்க்',
    navItemAddElector: 'வாக்காளரைச் சேர்க்கவும் (வார்டு 02)',
    navItemFieldRecord: 'என் ஃபீல்ட் பதிவு',
    navItemSignOut: 'சேஷனில் இருந்து வெளியேறு',
    mobileNavWarRoom: 'யுத்த அறை',
    mobileNavVoters: 'வாக்காளர்கள்',
    mobileNavStudio: 'ஸ்டுடியோ',
    mobileNavBroadcast: 'ஒளிபரப்பு',
    mobileNavFieldDesk: 'ஃபீல்ட் டெஸ்க்',
    navbarToggleSidebar: 'நேவிகேஷன் டிரய்ர் டாகிள் செய்க',
    navbarChangeLanguage: 'மொழியை மாற்றவும்',
    navbarLiveNotifications: 'நேரடி அறிவிப்புகள்'
  },
  gu: {
    commandCenter: 'ચૂંટણી પ્રચાર કમાન્ડ સેન્ટર',
    commandCenterSub: 'ગ્રામ પંચાયત રામપુર ચૂંટણી માટે લાઇવ ઓવરવ્યૂ.',
    campaignTeam: 'પ્રચાર ટીમ અને પરવાનગીઓ',
    teamDescription: 'મેનેજર અને બૂથ ઇન્ચાર્જ ઉમેરો.',
    candidateCenter: 'ઉમેદવાર વ્યવસ્થાપન કેન્દ્ર',
    candidateDescription: 'ઉમેદવાર પ્રોફાઇલ, ચૂંટણી પ્રતીક અને ઘોષણાપત્ર.',
    voterDatabase: 'મતદાર યાદી ડેટાબેઝ',
    voterDatabaseDesc: 'મતદાર યાદી વ્યવસ્થાપન અને કેમેરા OCR સ્કેનર.',
    studioTitle: 'ડિઝાઇન સ્ટુડિયો',
    studioSub: 'પોસ્ટર, ફ્લેક્સ બેનર અને વોટ્સએપ કાર્ડ બનાવો.',
    broadcastTitle: 'મેસેજિંગ અને બ્રોડકાસ્ટ સેન્ટર',
    broadcastSub: 'વોટ્સએપ અને SMS દ્વારા મતદારો સુધી પહોંચો.',
    boothOps: 'બૂથ કામગીરી',
    surveysComplaints: 'ફરિયાદો અને સર્વેક્ષણ',
    expensesLedger: 'ખર્ચ રજિસ્ટર',
    turnoutAnalytics: 'મતદાન વિશ્લેષણ',
    settingsBranding: 'સેટિંગ્સ અને બ્રાન્ડિંગ',
    totalVoters: 'કુલ મતદારો',
    whatsappReached: 'વોટ્સએપ પહોંચ',
    activeTeam: 'સક્રિય ટીમ',
    budgetUtilized: 'ખર્ચાયેલ બજેટ',
    searchVoters: 'મતદાર શોધો...',
    allSegments: 'બધા મતદારો',
    exportCsv: 'CSV ડાઉનલોડ',
    uploadRoll: 'યાદી અપલોડ કરો',
    scanOcr: 'OCR સ્કેન',
    addCandidate: '+ ઉમેદવાર ઉમેરો',
    addMember: '+ સભ્ય ઉમેરો',
    logGrievance: '+ ફરિયાદ નોંધો',
    addExpense: '+ ખર્ચ ઉમેરો',
    dispatchBroadcast: 'મેસેજ મોકલો',
    dontHaveAccount: 'ખાતું નથી? સાઇન અપ કરો',
    alreadyAccount: 'પહેલેથી ખાતું છે? લૉગિન કરો',
    continueDemo: 'ડેમો મોડ ચાલુ રાખો',
    roleSwitcher: 'રોલ બદલો',
    dashboardOverview: 'ડેશબોર્ડ ઓવરવ્યૂ',
    currentElection: 'હાલની ચૂંટણી',
    totalCandidatesOrganizations: 'કુલ ઉમેદવાર / સંસ્થાઓ',
    candidatesAndOrganizations: 'ઉમેદવાર અને સંસ્થાઓ',
    totalVotersAdded: 'જોડાયેલા કુલ મતદારો',
    liveVoterDatabase: 'લાઇવ મતદાતા ડેટાબેઝ',
    activeElections: 'સક્રિય ચૂંટણીઓ',
    electionPortfolio: 'ચૂંટણી પોર્ટફોલિયો',
    recentActivity: 'તાજી પ્રવૃત્તિ',
    latestUpdates: 'સૌચિન અપડેટ્સ',
    last5Updates: 'છેલ્લા 5 અપડેટ્સ',
    type: 'પ્રકાર',
    details: 'વિગત',
    time: 'સમય',
    totalVotersInElection: 'ચૂંટણીમાં કુલ મતદારો',
    volunteersCount: 'સ્વયંસેવકો',
    activeVolunteers: 'સક્રિય સ્વયંસેવકો',
    messagesSentThisWeek: 'આ અઠવાડિયામાં મોકલેલા સંદેશાઓ',
    campaignReach: 'પ્રચાર પહોંચ',
    wardCoverage: 'વાર્ડ-વચિત કવરેજ',
    coverageSummary: 'કવરેજ સારાંશ',
    quickActions: 'ઝડપી ક્રિયાઓ',
    dailyChecklist: 'દૈનિક ચેકલિસ્ટ',
    addVoter: 'મતદાર ઉમેરો',
    createPoster: 'પોસ્ટર બનાવો',
    sendBroadcast: 'બ્રોડકાસ્ટ મોકલો',
    viewComplaints: 'ફરિયાદો જુઓ',
    wardVotersCount: 'વાર્ડ મતદારો',
    wardCoverageSummary: 'તમારો વાર્ડ કવરેજ',
    pendingTasks: 'બાકી કાર્યો',
    todayChecklist: 'આજની યાદી',
    taskSummary: 'કાર્ય સારાંશ',
    assignedVoters: 'નિયુક્ત મતદારો',
    assignedVoterSummary: 'ફોલો-અપ યાદી',
    dashboardLoadError: 'બેકએન્ડમાંથી ડેટા લોડ થઈ શક્યો નથી',
    candidates: 'ઉમેદવાર',
    organizations: 'સંસ્થાઓ',
    volunteers: 'સ્વયંસેવકો',
    recent: 'સજાવટ',
    // Auth Form
    createAccount: 'ખાતું બનાવો',
    signIn: 'સાઇન ઇન',
    registerVerifiedAccount: 'ચકાસાયેલ પ્રચાર ખાતું નોંધાયું કરો',
    enterCredentials: 'ડેશબોર્ડ અ્ક્સેસ કરવા માટે તમારી શક્તિશાલી તત્વો દાખલ કરો',
    firstName: 'પ્રથમ નામ',
    enterFirstName: 'પ્રથમ નામ દાખલ કરો',
    lastName: 'અંતિમ નામ',
    enterLastName: 'અંતિમ નામ દાખલ કરો',
    emailAddress: 'ઇમેલ સરનામું',
    password: 'પાસવર્ડ',
    createPassword: 'પાસવર્ડ બનાવો',
    enterPassword: 'તમારો પાસવર્ડ દાખલ કરો',
    authenticating: 'પ્રમાણીકરણ...',
    creatingAccount: 'ખાતું બનાવી રહ્યું છે...',
    or: 'અથવા',
    alreadyHaveAccountLogin: 'પહેલેથી ખાતું છે? સાઇન ઇન',
    quickDemoLogin: '🎯 ઝડપી ડેમો લૉગઇન (સુપર એડમિન)',
    signUpNewAccount: 'નવું ખાતું બનાવવા માટે સાઇન અપ કરો',
    multiTenantNote: 'મલ્ટી-ટેનંટ · JWT પ્રમાણીકરણ · અનુમતિ-આધારિત RBAC',
    realTimeElection: 'રીયલ-ટાઇમ ચૂંટણી પ્રચાર વ્યવસ્થાપન',
    voterDataVolunteer: 'મતદાતા ડેટા · સ્વયંસેવક વ્યવસ્થાપન · ડિજાઇન સ્ટુડિયો · સ્માર્ટ પ્રસારણ · વિશ્લેષણ ડેશબોર્ડ',
    roleBasedAccess: 'ભૂમિકા-આધારિત પ્રવેશ નિયંત્રણ (RBAC)',
    multiTenantOrg: 'મલ્ટી-ટેનંટ સંસ્થા અલગીકરણ',
    realtimeDashboard: 'રીયલ-ટાઇમ ડેશબોર્ડ અને વિશ્લેષણ',
    masterCampaignOS: '🇮🇳 મીસ્ટર પ્રચાર OS અને યુદ્ધ ક્ષેત્ર',
    // Form validation
    fieldRequired: 'આ ક્ષેત્ર જરૂરી છે',
    invalidEmail: 'કૃપયા માન્ય ઇમેલ દાખલ કરો',
    passwordMismatch: 'પાસવર્ડ મેળ ખાતા નથી',
    // Success/Error messages
    welcomeMessage: 'ElectWin યુદ્ધ ક્ષેત્રમાં સ્વાગત છે!',
    enteredAsAdmin: 'સુપર એડમિન તરીકે ElectWin માં પ્રવેશ કર્યો (ડેમો મોડ)',
    accountCreated: 'ખાતું બન્યું. કૃપયા તમારી શક્તિશાલી તત્વો સાથે સાઇન ઇન કરો.',
    invalidCredentials: 'અમાન્ય ઇમેલ અથવા પાસવર્ડ.',
    backendNotRunning: 'ડેમો લૉગઇન નિષ્ફળ — ખાતરી કરો કે બેકએન્ડ પોર્ટ 8000 પર ચાલુ છે.',
    signUpFailed: 'સાઇન અપ નિષ્ફળ.',
    // Common actions
    save: 'બચાવો',
    cancel: 'રદ કરો',
    delete: 'હટાવો',
    edit: 'સંશોધન કરો',
    close: 'બંધ કરો',
    submit: 'સબમિટ કરો',
    back: 'પાછું',
    next: 'આગલું',
    // Table actions
    action: 'ક્રિયા',
    status: 'સ્થિતિ',
    name: 'નામ',
    email: 'ઇમેલ',
    phone: 'ફોન',
    date: 'તારીખ',
    // Dashboard specific
    totalVotersReachable: 'કુલ મતદાતા (પહોંચી શકાય)',
    broadcastsDispartched: 'પ્રસારણ મોકલવામાં આવ્યાં',
    successRate: 'સફળતાનો દર',
    teamMembersCount: 'ટીમ સભ્યોની સંખ્યા',
    // Navigation items
    navigationSidebarCampaignMgmt: 'પ્રચાર વ્યવસ્થાપન',
    navigationSidebarFieldVolunteer: 'ફીલ્ડ સ્વયંસેવક ડેસ્ક',
    navItemWarRoomDashboard: 'યુદ્ધ ક્ષેત્ર ડેશબોર્ડ',
    navItemTeamPermissions: 'ટીમ અને પરવાનગીઓ',
    navItemCandidatesSymbols: 'ઉમેદવાર અને પ્રતીક',
    navItemVoterRollOCR: 'મતદાર યાદી અને OCR',
    navItemDesignStudio: 'ડિઝાઇન સ્ટુડિયો',
    navItemBroadcastCenter: 'પ્રસારણ કેન્દ્ર',
    navItemBoothOperations: 'બૂથ કાર્યક્રમ',
    navItemSurveysGrievances: 'સર્વે અને ફરિયાદો',
    navItemECExpensesLedger: 'ખર્ચ રજિસ્ટર',
    navItemTurnoutAnalytics: 'મતદાન વિશ્લેષણ',
    navItemSettingsBranding: 'સેટિંગ્સ અને બ્રાન્ડિંગ',
    navItemWardFieldDesk: 'વાર્ડ 02 ફીલ્ડ ડેસ્ક',
    navItemAddElector: 'મતદાતા ઉમેરો (વાર્ડ 02)',
    navItemFieldRecord: 'મારો ફીલ્ડ રેકોર્ડ',
    navItemSignOut: 'સેશનથી સાઇન આઉટ કરો',
    mobileNavWarRoom: 'યુદ્ધ ક્ષેત્ર',
    mobileNavVoters: 'મતદાતા',
    mobileNavStudio: 'સ્ટુડિયો',
    mobileNavBroadcast: 'પ્રસારણ',
    mobileNavFieldDesk: 'ફીલ્ડ ડેસ્ક',
    navbarToggleSidebar: 'નેવિગેશન ડ્રોઅર ટૉગલ કરો',
    navbarChangeLanguage: 'ભાષા બદલો',
    navbarLiveNotifications: 'લાઇવ નોટિફિકેશન'
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    return (localStorage.getItem('electwin_lang') as LanguageCode) || 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('electwin_lang', lang);
  };

  const t = (key: string): string => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.en;
    return dict[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
